### ISSUE TITLE
PDF with invalid mimetype fails in via

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#102]
This PDF:

https://via.hypothes.is/https://www.heartland.org/_template-assets/documents/Books/Why%20Scientists%20Disagree%20Second%20Edition%20with%20covers.pdf

Fails in via.

Per @nickstenning:

"doesn't work because it's served with the invalid mimetype `application/pdf;charset=UTF-8` (which doesn't make any sense at all) instead of `application/pdf`and via isn't smart enough to ignore the invalid `charset` parameter"

**Comment by sean-roberts** [comment]
This is deployed now. If you are still seeing the same behavior, it is likely a cdn cache issue and will resolve itself for everyone using that cdn node in a couple of hours. You can modify the url slightly like this:

https://via.hypothes.is/https://www.heartland.org/_template-assets/documents/Books/Why%20Scientists%20Disagree%20Second%20Edition%20with%20covers.pdf?cachebust

to get around that for the time being - if you even have this issue
