### ISSUE TITLE
Display error details if transcript fails to load

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#1028]
If an error occurs loading a transcript, the video player currently displays a generic and unstyled message:

<img width="425" alt="Transcript error" src="https://github.com/hypothesis/via/assets/2458/1983df95-e14f-4505-aceb-d2b548110053">

Instead it should display something more informative using the error details returned from the backend. In the case of https://www.youtube.com/watch?v=dNrTrx42DGQ the details returned are:

(_Update: This video now *does* have a transcript. It is a long video that had only just been uploaded when I initially reported this. Try https://www.youtube.com/watch?v=e-43x-H4CNY instead, which is a video that inherently has no spoken content._)

```json
{
    "errors": [
        {
            "status": 500,
            "code": "TranscriptsDisabled",
            "title": "Subtitles are disabled for this video",
            "detail": "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=dNrTrx42DGQ! This is most likely caused by:\n\nSubtitles are disabled for this video\n\nIf you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!"
        }
    ]
}
```

We should avoid including `detail` verbatim here because it references the Python library we currently use.

The value of the `code` field above comes from the names of error classes in https://github.com/jdepoix/youtube-transcript-api/blob/master/youtube_transcript_api/_errors.py.

**Comment by robertknight** [comment]
I had a query about the HTTP status here. That is being discussed in https://hypothes-is.slack.com/archives/C1MA4E9B9/p1688120133798219.

**Comment by lyzadanger** [comment]
Given that this type of error is non-recoverable — the app is not usable when these happen — I'd suggest we not use the toast pattern and instead have a persistent error. We can still style it consistently using the `Callout` component from the `frontend-shared` package[^1], which drops in easily:

```jsx
<div data-testid="transcript-error">
  <Callout status="error">
    Unable to load transcript: {transcript.message}
  </Callout>
</div>
```

That looks like this:

<img width="519" alt="image" src="https://github.com/hypothesis/via/assets/439947/0f439214-1b49-4d94-8403-439297c1c460">


[^1]: Not yet published with this component. We need to merge https://github.com/hypothesis/frontend-shared/pull/1125 and cut a new release to make this component available. NBD.

**Comment by robertknight** [comment]
What happens if you click on the "X" here? Presumably nothing? But it looks like it wants to be clicked!

**Comment by lyzadanger** [comment]
> What happens if you click on the "X" here? Presumably nothing? But it looks like it wants to be clicked!

Ah! Interested observation. Fortunately this component will take a custom `icon` prop so we could use a "caution" icon here instead, or something.

**Comment by robertknight** [comment]
We have landed an initial version of this, and https://github.com/hypothesis/via/pull/1049 improves the styling.
