### ISSUE TITLE
Route by content end-point should preserve encoded chars (including commas)

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#105]
Things to test:

* Does it request the URL correctly when checking the type?
* If it's PDF does it redirect correctly?
* If it's not a PDF does it redirect correctly?

As commas and spaces behave differently, we should check that we preserve escaping for both if present.

We believe it is ok to add encoding where it was not before, but not ok to remove it.

**Comment by jon-betts** [comment]
This is all testing well right now. I'm going to look at whether we have / need some tests to cover this.
