### ISSUE TITLE
Check / refine behavior of tapping segments to select them on Android

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#1059]
In https://github.com/hypothesis/via/pull/1058#pullrequestreview-1522079650 @acelaya reported that the new behavior of clicking segment texts to seek to a segment worked well on desktop, but not on Android. This issue is about clarifying the current behavior of clicking segments to select them and refining as needed. See the original PR for an explanation of the desired behavior and how it interacts with text selection.

Steps to test:

1. View a video in Via, eg. https://qa-via.hypothes.is/https://www.youtube.com/watch?v=TbzZIMQC6vk
2. Scroll the transcript and tap the text for a segment. The tapped segment should become current and the video should seek.
3. Now long-press a different non-current segment to start a text selection. It should not become current.
4. After making a selection, tap a different non-current segment to clear the selection and hide the Annotate/Highlight popup. The tapped segment should not become current.

**Comment by robertknight** [comment]
I've tested the behavior on iOS 16, it works as intended there. Tapping a segment makes it current. Long-pressing a segment to initiate a text selection, or tapping to clear, does not make it current. The ideal behavior on Android should be the same.

**Comment by acelaya** [comment]
Some versions back, that was also the behavior on Android. The only way to select text was by long-pressing.

Now, it seems to try to be smart and assume you want to select text when tapping the screen, and it finds a word on that spot.

**Comment by robertknight** [comment]
> Now, it seems to try to be smart and assume you want to select text when tapping the screen, and it finds a word on that spot.

It would be useful to know more details about when this changed and whether there are any system settings that affect the behavior. Since selecting text is an integral part of using Hypothesis, it seems useful to have a good understanding of this.

**Comment by robertknight** [comment]
Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1690811850939109

**Comment by robertknight** [comment]
Per discussion in above Slack thread, we think the current behavior is usable and agreed to close this issue for now.
