### ISSUE TITLE
Video annotation issue in Canvas w/ Side by side mode

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#1086]
There's a little issue when in Canvas w/ video annotation.  Clicking on the transcript to select auto-closes the sidebar.  Here's a short video that demonstrates.
[Video annotation bug inside Canvas](https://share.vidyard.com/watch/a23YJ4RAyy7UEUBLQ5wgss?)
Video annotation bug inside Canvas

This is the assignment I was on.  By the way I had "student view" enabled.  Not sure if that makes a difference.
https://hypothesis.instructure.com/courses/125/assignments/4994

**Comment by robertknight** [comment]
> Clicking on the transcript to select auto-closes the sidebar.

This is a temporary issue while we're transitioning to a new implementation of side-by-side in the video player. Will be fixed soon by https://github.com/hypothesis/via/pull/1083.

**Comment by dwhly** [comment]
Gotcha tx!

**Comment by acelaya** [comment]
This should be fixed now.
