### ISSUE TITLE
Serve longer C-C headers on archived pages

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/via#11]
Once a page is archived we can serve it with some decent `cache-control` headers for CloudFlare's benefit. Before I just go ahead and do this are there any considerations I need to make about what not to cache @ikreymer?

**Comment by ikreymer** [comment]
I'm not sure what you mean.. archiving through via itself? or something else? Probably via shouldn't be cached at all, but in an archived replay, that'd be different...

**Comment by ikreymer** [comment]
Maybe I'm not fully understanding the use case..

**Comment by nickstenning** [comment]
Sorry, my fault -- I didn't make my issue clear. The question is about serving via behind a CDN (in our case, CloudFlare), and trying to offload some of the traffic to the CDN rather than the via Python application. If I use via to navigate to:

    http://www.bbc.com

I get to a URL such as:

    https://via.hypothes.is/20150506170421/http://www.bbc.com

It appears that I can share this with others. If that's true, then we can offload traffic from via itself by serving these pages with longer C-C headers. If we do that, the pages will be cached by CloudFlare and served without communicating with the origin server.

Is that a terrible idea for reasons I haven't considered?

**Comment by tilgovi** [comment]
I can break down two questions:

1) Does via pass through any caching headers sent by the origin (etags, cache-control, etc)

2) Should via sent headers which differ from those?

I'll note that for (2) CloudFare can actually do that itself, and in doing so it can relieve a lot of load even with no help from the origin server, I think.

**Comment by ikreymer** [comment]
Ahh ok I think I have a better understanding.. for me, 'cached' vs 'archived' mean very different things :)
pywb rewrites certain headers, and I think that includes C-C for now, so I think it will rewrite these by default. Should probably add a way to customize header pass-through, which shouldn't be too bad.

I think cacheing with CloudFlare does make sense for this, I suppose it'd only be an issue if there are many changes to a page (a news story?)

**Comment by ikreymer** [comment]
I'm not familiar with CloudFlare config, but maybe sounds like it may make sense to try it uniformly against all sites? The rewritten heads are of the form`X-Archive-[original header'` so would be `X-Archive-Cache-Control`

**Comment by tilgovi** [comment]
I wonder if for the live rewriter use case it makes more sense to pass through caching related headers unmolested.

**Comment by tilgovi** [comment]
AFAIK we can't tell CloudFlare (or any other proxy I know about) to treat non-standard headers as having standard cache control meaning. We would need to pass them through.

**Comment by nickstenning** [comment]
The URLs that via generates are already timestamped, so I'm not sure
passthrough
is necessary or appropriate. Simply setting a fixed C-C header should be
fine, no?

**Comment by tilgovi** [comment]
They're timestamped? I don't see that.

**Comment by nickstenning** [comment]
You're right. Most pages I try aren't. I don't understand why there's a difference. If I type "bbc.co.uk" I end up at `https://via.hypothes.is/20150507195839/http://www.bbc.com`. The same isn't true for "nytimes.com". Is this to do with pages that serve a redirect? @ikreymer?

**Comment by ikreymer** [comment]
Yeah, when it redirects it adds the current timestamp, but looks like it does not do that otherwise..
Seems like that should probably change.. it should either have a timestamp always, or never?
Thoughts?

**Comment by tilgovi** [comment]
I think maybe never?

How granular are the timestamps? If they're too granular they won't really cache usefully.

**Comment by ikreymer** [comment]
Timestamps are per second.. Yeah, probably easiest to turn them off altogether.. since linking to an older timestamp doesn't really make sense anyway in this case.

**Comment by ikreymer** [comment]
in fact, i think that is a bug anyway.. there shouldn't have been any, its the redirect that causes them to be added... So, for this issue we need:
- no timestamps on redirect
- pass through `Cache-Control`, other cache headers unchanged, right?

**Comment by tilgovi** [comment]
I think so. Does this sound right:

- `Cache-Control`
- `ETag`
- `Expires`
- `Last-Modified`

and we need to be sure that `If-*` is passed to the upstream, if it isn't already.

This is useful to reference here, perhaps: http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.5.2

**Comment by ikreymer** [comment]
Latest via config (https://github.com/hypothesis/via/commit/52815c6b53ee1524f3022211e3562afffb219486) now has `http_cache: pass` option, which will pass-through any cache headers w/o rewriting. Alternatively, they can be explicitly set with `http_cache: N` which will result in `max-age=N` being set on all resources.

**Comment by tilgovi** [comment]
Cool!
