### ISSUE TITLE
In LMS assignments: Play icon only works once YouTube player has been interacted with

### ISSUE THREAD

**Issue by nairiboo** [hypothesis/via#1136]
Post release feedback:

The "Play" button at the top of the transcript sidebar doesn't work if you try to use it to initially play the video. after you play the video from actual video, the "pause/play" button on the transcript works, just not that very first time.

**Comment by robertknight** [comment]
The "Play" button should work if clicked as soon as the page loads. I was not able to reproduce the issue at https://qa-via.hypothes.is/https://www.youtube.com/watch?v=x8TO-nrUtSI in Chrome, Safari or Firefox. I did however experience a problem within an LMS assignment, where the video player is embedded in a cross origin iframe.

I tested with https://hypothesis.instructure.com/courses/125/assignments/5110.
