### ISSUE TITLE
Still injecting H on child iframes

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#119]
To repro:
1 - Go here: https://via.hypothes.is/https://www.newyorker.com/magazine/2017/12/11/success-academys-radical-educational-experiment
2- Notice that H is being injected into the audio sub-iframe.
3- Also notice that the bucket bar shows "2" annotations when there appears to be only 1 public test annotation (mine).

(related support ticket https://hypothesis.zendesk.com/agent/tickets/1857)

Also, possibly related to https://github.com/hypothesis/via/pull/118

D

**Comment by judell** [comment]
Also here as reported by Climate Feedback: https://via.hypothes.is/https://www.breitbart.com/politics/2019/04/09/nolte-scientists-prove-man-made-global-warming-is-a-hoax/
