### ISSUE TITLE
broken image display in popup window

### ISSUE THREAD

**Issue by judell** [hypothesis/via#13]
At http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4403968/#!po=22.0000, Figure 1 displays in a popup.

At https://via.hypothes.is/http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4403968/#!po=22.0000 the image does not display because the relative URI, /pmc/articles/PMC4403968/bin/nbm0028-0468-f1.jpg, has not been rewritten.

Here's why it was not:

```
<a class="icnblk_img figpopup" 
href="https://via.hypothes.is/http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4403968/figure/fig01/?report=objectonly" 
rid-figpopup="fig01" rid-ob="ob-fig01" target="_blank" co-class="co-fig">
<img src="https://via.hypothes.is/im_/http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4403968/bin/nbm0028-0468-f1.gif" class="small-thumb" alt="Figure 1" title="Figure 1" 
src-large="/pmc/articles/PMC4403968/bin/nbm0028-0468-f1.jpg">
</a>
```
There is no such attribute on the img tag as src-large.

**Comment by tilgovi** [comment]
I suspect it's totally unwise to start supporting non-standard attributes, which I think `src-large` would be.

However, we could maybe support relative URLs in unexpected places with some reliability by ensuring that we rewrite or insert (when it's missing) a base tag.

**Comment by tilgovi** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by judell** [comment]
100% agree not to support non-standard attributes.

Rewriting relative URLs sounds plausible but I wonder what dragons lurk in *unexpected places*.

**Comment by tilgovi** [comment]
Yeah, same. From experience, I know that Firefox and Chrome handle the base tag slightly differently. For instance, having it will break relative references in SVGs that come from a different origin, but if the goal is to proxy everything through via then having the base tag point at the root of the via URL that's loaded might be pretty safe.

**Comment by ikreymer** [comment]
The client side rewriting should already catch this if its being loaded into a standard attribute later. Looks like this is working in the latest dev version: http://pywb-h.herokuapp.com/http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4403968/

**Comment by ikreymer** [comment]
Now fixed

**Comment by judell** [comment]
What was the fix?
