### ISSUE TITLE
Performance test Via 3 PDF proxying

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#13]
Test the performance of Via 3 PDF proxying -- what is the speed of the user experience.

Before we do this we should add a "do not inject the client" feature flag to Via 3 so that we can performance test Via 3 without the client. Otherwise the client's load time and all its requests and resources get in the way.

TODO: Add more details to this issue.

**Comment by dmfine** [comment]
Is there a part of this for me to do?

**Comment by seanh** [comment]
Closing as not gonna bother
