### ISSUE TITLE
via redirects every site on minds.com to it's login page

### ISSUE THREAD

**Issue by Serkan-devel** [hypothesis/via#130]
If I try to view any page on https://via.hypothes.is/https://www.minds.com/
it gets redirected to https://via.hypothes.is/https://www.minds.com/login

Minds.com is an alternative open source social network, currently being used by many Vietnamese people do newly introduced regulations, which makes facebook more harmful

**Comment by klemay** [comment]
Via can't access sites behind a login - see: https://web.hypothes.is/help/why-cant-i-log-in-to-a-website-using-via/

> If you would like to log in to a website that you are visiting using Via, please access the page directly, log in, and use the extension or bookmarklet to annotate.

**Comment by Serkan-devel** [comment]
Umm, no. One isn't required to log into minds to view content (except seetings or paywalls).

Example:
This https://www.minds.com/media/281830469262118912 works normally
This https://via.hypothes.is/https://www.minds.com/media/281830469262118912 redirects to the login

It's not much different than FB or twitter

**Comment by klemay** [comment]
Keeping this closed for now given this issue is being discussed in our open Slack channel ([see discussion starting here](https://hypothesis-open.slack.com/archives/C6Y375TT3/p1531842413000059)) and Andrew's observation of the following:

> When I try that link, there is a delay. I see the content, then a second later I’m redirected to the login screen. This makes me think it’s something coded into Minds that is causing the redirect.

**Comment by Serkan-devel** [comment]
The only way, I came to the login screen on the normal browser is by typing `document.getElementsByTagName('button')[0].click();`. Are there any button presses when displaying a site?

**Comment by Serkan-devel** [comment]
But is your IRC channel on freenode still maintained, or has it really been moved?

**Comment by klemay** [comment]
Hi there,

We had to temporarily disable the freenode integration for our public Slack
workspace because of the spambot attacks that happened last week (see:
https://freenode.net/news/spambot-attack).

I’m planning to turn it back on tomorrow and monitor closely.

-Katelyn

**Comment by Serkan-devel** [comment]
Would you consider moving the IRC channel to another host?

**Comment by klemay** [comment]
Apart from this one instance, Freenode has worked well for us. The
integration is turned back on so you should be able to ask questions via
IRC again.
