### ISSUE TITLE
Q: Can I remove Authorization, Cookie.. of REQUEST_HEADER_BLACKLIST in security.py?

### ISSUE THREAD

**Issue by lnguyen0901** [hypothesis/via#131]
I cannot login when using via hypothesis. I research and found the solution by removed/commented some values in via/security.py as: Authorization, Cookie, X-Csrf-Token, Set-Cookie.
So, can I remove Authorization, Cookie.. of REQUEST_HEADER_BLACKLIST in security.py? What is problem when I removed that values?

**Comment by robertknight** [comment]
Via prevents websites from setting cookies because this would make session credentials for one website (eg. https://via.hypothes.is/twitter.com) visible not only to the operators of Via (us) but also to other websites visited through Via (eg. https://via.hypothes.is/evil.com).

If you are running your own Via instance for your personal use then you can change the blacklist. We are not likely to change these restrictions in the production service at https://via.hypothes.is though.

**Comment by lnguyen0901** [comment]
Thank you for your quick answer.
I running my own via instance for my personal.

**Comment by lnguyen0901** [comment]
@robertknight 
I'm sorry for reopening my question.
As you said about "the session credentials for one website it would be visible not only to the operators of Via...". Could you give me an evidence or the case it happened?

Why I want an evidence from you?
Because I tried to read cookies from other websites visited through Via (of course in My own Via) but can  not read the cookies.
Here is my procedures:
1. Login from A site. The session credentials would be saved to cookies in browsers.
2. Visit to B site, try to read session credentials from cookies that saved in A site.

I'm appreciate from your help.

**Comment by robertknight** [comment]
> As you said about "the session credentials for one website it would be visible not only to the operators of Via...". Could you give me an evidence or the case will happened?

This is a fundamental issue with proxies and the way security on the web works - where data is isolated by origin (protocol + host + port). You can see the issue by using JS to read/write cookies:

1. Go to https://via.hypothes.is/example.org
2. Open the browser JS console and run `document.cookie="example.org=foo"`
3. Go to https://via.hypothes.is/example.com (a _different_ site)
4. Open the browser JS console and run `document.cookie` - you'll see that the "example.org" cookie is still there.

This problem affects other data that is partitioned by origin too, such as local storage, IndexedDB, permissions and many other things I haven't listed here. Cookies are just the most obvious one.
