### ISSUE TITLE
Question: Does via download the assets (js, html, etc..) and saves on HD?

### ISSUE THREAD

**Issue by yattias** [hypothesis/via#132]
Hi Hypothesis team,

I'm trying to assess if via is a good solution for us. Glad you made it - it is awesome.

Does via download the assets (js, html, etc..) and saves on HD?

Thank you.

**Comment by robertknight** [comment]
Hello @yattias, sorry for the delayed response. Via does not cache any assets that pass through it. It fetches the proxied resources from the original web server each time.
