### ISSUE TITLE
NGINX should be a process not a service, in dev

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#134]
Currently `make services` runs NGINX whereas `make dev` runs the Python app. While `make services` makes sense as a way to run PostgreSQL, Elasticsearch, and RabbitMQ in h and lms, it doesn't really make sense as a way to run NGINX in via3. In via3, NGINX is really part of the app itself, rather than a separate service that the app depends on. It should therefore be run by `make dev`.

Done when:

- [ ] Via 3 no longer has a `make services` command (or `make services` is a no-op)

- [ ] Running `make dev` in Via 3 runs both NGINX and the Pyramid app in a single shell using a process multiplexer.

  `make services` currently uses Docker Compose to run NGINX. Docker Compose may or may not make sense as the way for `make dev` to run NGINX. It may make more sense for `make dev` to call `docker` directly.

  All of our other apps use Honcho to run multiple processes at once in dev. Honcho is _very_ easy to set up so copying that should be quick and easy. But we're not very happy with how Honcho is performing for us, so we may want to take this as an opportunity to try using Supervisor within a project repo instead.

- [ ] The new way of running things has been updated in `superdev`

- [ ] Bonus points: any changes to the NGINX config file (or any files that NGINX or the NGINX config depends on) triggers an automatic restart of the NGINX process that `make dev` is running.

  This one could be moved to a separate card, allowing this card to be closed without it.

**Comment by jon-betts** [comment]
I'm happy with all that (not quite sure how the auto-reloading would work). 

I'm glad we're on the same page now, but is there a specific problem you were having with this that prompted the ticket? Just trying to get an idea of priority.

I don't think we want to increase our honcho usage if we can avoid it. It would be interesting to see if an idea I'd had before would work, which is if projects had their own supervisor configs, if we could pull them directly into superdev, rather than have it maintain a master for them all.

**Comment by seanh** [comment]
> I don't think we want to increase our honcho usage if we can avoid it. It would be interesting to see if an idea I'd had before would work, which is if projects had their own supervisor configs, if we could pull them directly into superdev, rather than have it maintain a master for them all.

I think let's just stick with Honcho for ease and for consistency with our other apps. It's what we already use in every app that requires `make dev` to run multiple processes. Honcho is **very** simple to add to an app and to understand, and it does exactly what we want. All you need is a `Procfile` (extremely simple file format) and then you just run `honcho`. We've used Honcho across all our apps (bouncer, h, lms and via all use it) for many years and never had a problem or complaint. I did previously blame honcho for weird issues that `make dev` was having, but those turned out to be caused by pserve not Honcho.

Regarding pulling process multiplexer configs from the individual apps up into a master project: this is already possible based on the Honcho `Procfile`'s that the apps contain. If the master project used Honcho, it's little more than just concatenating the `Procfile`'s together and then running `honcho`. There's a little more to it than that, but not much. If the master project used supervisor instead like superdev does, then I'd recommend the master project contain a script for parsing the `Procfile` (_very_ easy) and exporting it to a supervisor conf file. I think there may even be Procfile -> supervisor export tools out there already. But one would be very easy to write
