### ISSUE TITLE
via breaks disqus

### ISSUE THREAD

**Issue by judell** [hypothesis/via#14]
Jeremy Dean reports: 

```
compare this via link:

https://via.hypothes.is/chronicle.com/blogs/profhacker/how-do-you-annotate-in-your-class/60101

with this regular URL for same article:

http://chronicle.com/blogs/profhacker/how-do-you-annotate-in-your-class/60101*
```

(Even more severe breakage at https://disqus.com/home/discussion/channel-plotthreads/actors_do_we_still_need_them/)

**Comment by ikreymer** [comment]
I've been working on a few fixes in pywb, which fix disqus on the first page: http://pywb-h.herokuapp.com/chronicle.com/blogs/profhacker/how-do-you-annotate-in-your-class/60101

Will take a look at the disqus.com, hopefully fixable w/o too much trouble.

**Comment by ikreymer** [comment]
ok, disqus is going to be tricky.. the site does the thing where it wipes the whole DOM, and reinits it dynaymically, so will need some way to readd the hypothesis toolbar after the page has loaded.. also, it loads custom fonts that i think break the icons (this happens even with plugin).
But it is 'proxyable' with a bit of effort:
http://pywb-h.herokuapp.com/https://disqus.com/home/discussion/channel-plotthreads/actors_do_we_still_need_them/

**Comment by ikreymer** [comment]
Related to this, i think perhaps it would be possible to plan for building an integration/testing system for via/pywb.., maybe something that can be deployed to https://saucelabs.com/ ? I could work on it after my current grant project, and maybe you guys could spare a few cycles as well.. To start, would want to test that a few key sites to ensure that toolbar and annotations show up, and then can keep adding to it as needed.. any thoughts on this @judell ?

**Comment by tilgovi** [comment]
You should, I think, not try to handle the page that wipes itself clean in via.

**Comment by tilgovi** [comment]
For instance, we might want to watch this generally in h, and re-add ourselves if the page destroys us.

**Comment by ikreymer** [comment]
Agreed.. yeah, i think it would be better handled if h could detect this directly.. since it can happen outside of via too

**Comment by judell** [comment]
@ikreymer I would love to collaborate with you on Selenium testing. I've made a start in that direction, still unsure what's possible with reasonable effort, but want to explore further.

**Comment by ikreymer** [comment]
Disqus comments finally fixed: https://via.hypothes.is/chronicle.com/blogs/profhacker/how-do-you-annotate-in-your-class/60101

**Comment by judell** [comment]
Thanks! (What was the fix, btw?)

**Comment by ikreymer** [comment]
Just better, more accurate rewriting :) If I remember correctly, I think this had to do with inter-frame communication with `postMessage`.. It is now overwritten in a better way, such that different iframes think they are communicating with different hosts, when in fact the host is still `via.hypothes.is`
