### ISSUE TITLE
Prevent via3.hypothes.is from appearing on activity pages

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#145]
**(IMPORTANT - See [caveat below](https://github.com/hypothesis/via3/issues/145#issuecomment-644536582) about fixing this issue - @robertknight)**

Some annotations of PDFs are appearing on activity pages with via3.hypothes.is as the annotation's URL: <https://hypothes.is/search?q=via3.hypothes.is>

This would never normally happen in the LMS context because annotations are created in the LMS authority so they don't appear on activity pages (activity pages only show annotations from the default "hypothes.is" authority). The LMS annotations are still probably being created with the wrong URLs though--just not showing on activity pages.

Nonetheless we somehow still do have [some via3.hypothes.is annotations showing on activity pages](https://hypothes.is/search?q=via3.hypothes.is). This must be due to either people using https://via3.hypothes.is/ directly, or people who're using the LMS app with an application instance that has the "provisioning" setting disabled (which causes the LMS app to use the default authority).

Anyway, annotations created using Via 3 need to have the PDF's original URL as the annotation URL, not the via3.hypothes.is URL. Legacy Via does this somehow, so copy what it does

**Comment by seanh** [comment]
There does appear to be a `link rel="canonical"` tag in Via 3's PDF viewer's HTML, along with a comment that the client doesn't use it: https://github.com/hypothesis/via3/blob/838a70d67a93d81db749ae715c26f38cafd284c7/via/templates/pdf_viewer.html.jinja2#L7-L12

**Comment by robertknight** [comment]
The `VIA_DOCUMENT_URL` var assigned in the same script is the value that **is used**, by pdfjs-init.js. See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1588001562419400?thread_ts=1588001058.418400&cid=C4K6M7P5E.

**Comment by seanh** [comment]
So it looks like Via 3 needs to set `window.VIA_DOCUMENT_URL`, it doesn't currently

**Comment by robertknight** [comment]
When fixing this issue we need to be careful because there are users who already have annotations created which have Via 3 in the URL (eg. there are a bunch of annotations that have https://via3.hypothes.is/proxy/static/https://drive.google.com/uc?id=1VUFAu4vCHkNjOSe6AvfYoH8Up7dU_kZW&export=download as the URL). We need to make sure that when users visit these documents, any annotations that were made before the fix was deployed show up afterwards.

**Comment by robertknight** [comment]
This was caused by https://github.com/hypothesis/via3/issues/372. We fixed the issue for new annotations, but we still have existing annotations in the h database with correct `target_uri` values. This is covered by https://github.com/hypothesis/h/issues/6566.
