### ISSUE TITLE
Decide on Elastic Beanstalk instance type and number of Gunicorn workers, for production Via 3

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#15]
Before we can [Release Via 3 for production LMS users](https://github.com/hypothesis/py-proxy/issues/11) we need to set its Elastic Beanstalk instance type and its number of Gunicorn workers per instance. What should these be set to?

We might also want to ask what the best number of Nginx worker connections is? It's currently [set to 1024](https://github.com/hypothesis/py-proxy/blob/04ba2b220a53fe453e8d13e5ea93af058ac58ab0/nginx/nginx.conf#L7).

We should involve @robertknight and @dmfine in a discussion about this, to decide on good starting values for production Via 3.

**Comment by hmstepanek** [comment]
See [slack thread](https://hypothes-is.slack.com/archives/CR3E3S7K8/p1579029941019900) for documentation on these decisions.

- [x] t3.small
- [x] (2 x $num_cores) + 1
- [x] min number of instances: 4
- [x] max number of instances: 12 
- [x] auto scale based on number of requests

**Comment by hmstepanek** [comment]
These [things](https://github.com/hypothesis/py-proxy/issues/15#issuecomment-574823724) are all completed so I'm closing this.
