### ISSUE TITLE
Cloudflare doesn't like via

### ISSUE THREAD

**Issue by Treora** [hypothesis/via#15]
And that blocks a huge part of the web. For example, https://via.hypothes.is/http://cloudflare.com gives me:

![screenshot1](https://cloud.githubusercontent.com/assets/4191409/7902685/1eec0546-07ca-11e5-97f1-07a464f61ee2.png)

**Comment by tilgovi** [comment]
Is is because via itself is behind CloudFlare.

For now, absent a better solution, I've disabled CF on Via.
