### ISSUE TITLE
Favicon issues

### ISSUE THREAD

**Issue by JakeHartnell** [hypothesis/via#16]
I'm currently getting error this in my browser's console on pages [like this one](https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=/id_/http://www.jceps.com/wp-content/uploads/PDFs/10-2-03.pdf):
`GET https://via.hypothes.is/favicon.ico 503 (Service Unavailable)`

**Comment by ikreymer** [comment]
@nickstenning added a favicon in 3b80410b50b72da0dd0eba77fae9e5361a797555
