### ISSUE TITLE
Google Groups URL OK in H, not in Via

### ISSUE THREAD

**Issue by judell** [hypothesis/via#17]
For example, this works in the extension:

https://groups.google.com/a/hypothes.is/forum/#!topic/support/ZowpLBJp2F0/

(i.e, the page loads, an annotation anchors)

This fails:

https://via.hypothes.is/https://groups.google.com/a/hypothes.is/forum/#!topic/support/ZowpLBJp2F0/

(i.e., the page breaks completely)

The JS error is:

Failed to load resource: the server responded with a status of 503 (Service Unavailable) https://via.hypothes.is/forum/clear.cache.gif

**Comment by ikreymer** [comment]
At last, google groups should work (will be in next version of pywb, currently develop branch):

http://pywb-h.herokuapp.com/https://groups.google.com/forum/#!forum/hypothesis-forum

**Comment by ikreymer** [comment]
(The original link requires log-in, which due to the cookie safety change, won't work as login takes you to accounts subdomain and cookies are no longer preserved across domains)

**Comment by judell** [comment]
Thanks Ilya!

**Comment by ikreymer** [comment]
Now works: https://via.hypothes.is/https://groups.google.com/forum/#!forum/hypothesis-forum

**Comment by judell** [comment]
That's wonderful, thanks Ilya!
