### ISSUE TITLE
Un-deploy Via 2

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#17]
Since Via 3 replaces [Via 2 (a.k.a proxy-server)](https://github.com/hypothesis/proxy-server) (a previous attempt at replacing Via) we should un-deploy Via 2/proxy-server and remove it from our infrastructure, as part of the Via 3 project.

- [x] [Archive](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository) the https://github.com/hypothesis/proxy-server GitHub project
- [x] Remove proxy-server from Dependabot
- [x] Remove proxy-server from https://github.com/hypothesis/deployment
- [x] Remove proxy-server from Jenkins
- [x] Remove proxy-server from Elastic Beanstalk
- [x] Remove proxy-server ("Via2 Prod") from Papertrail
- [x] Remove via2 from Pingdom
- [x] Remove the via2 subdomain from Cloudflare
- [ ] Anything I missed?

**Comment by dmfine** [comment]
DO NOT UNDEPLOY UNTIL VIA3 is in prod. CHECK WITH SEAN

**Comment by seanh** [comment]
This is unblocked now -- Via 3 has been released to prod, nothing is using Via 2 / proxy-server anymore

**Comment by robertknight** [comment]
I had a quick look at this today. It looks to me like the following are done:

- Remove Via 2 / proxy-server from the deployment repo
- Remove proxy-server from Elastic Beanstalk

The following still needs to be done:

- Remove via2 from Cloudflare
- Remove proxy-server project from Jenkins
- Do a quick search for remaining references to `proxy-server` in the deployment and playbook repos

**Comment by dmfine** [comment]
Removed from cloudflare and jenkins, a search in repos did not turn up anything.
