### ISSUE TITLE
Un-deploy Injecture

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#18]
Since Via 3 replaces [Injecture](https://github.com/hypothesis/injecture) (a previous attempt at replacing Via) we should un-deploy Injecture and remove it from our infrastructure, as part of the Via 3 project.

- [x] [Archive](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository) the https://github.com/hypothesis/injecture GitHub project
- [x] Remove injecture from https://github.com/hypothesis/deployment
- [x] Remove injecture from Jenkins
- [x] Remove injecture from Elastic Beanstalk
- [x] Remove the injecture subdomain from Cloudflare
- [x] Remove injecture from https://github.com/hypothesis/playbook/ (it seems to be mentioned a couple of times in the terraform folder)
- [x] Anything I missed?

**Comment by dmfine** [comment]
Goodbye injecture. (removed stackoverflow mention too)
