### ISSUE TITLE
Site report: EdSurge.com

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#20]
https://via.hypothes.is/https://www.edsurge.com/n/2015-06-23-tom-vander-ark-why-private-capital-wins-out-over-philanthropic-capital-in-the-game-of-innovation

Anything to be done here?  via doesn't seem to play well. Just wondering if this is a class of problem that might be addressable.

**Comment by ikreymer** [comment]
Looks like this should work now, on the latest: https://pywb-h.herokuapp.com/https://www.edsurge.com/n/2015-06-23-tom-vander-ark-why-private-capital-wins-out-over-philanthropic-capital-in-the-game-of-innovation

I've updated via to pywb 0.10.0 a few weeks back, but not sure that a new via was ever deployed.. It should lead to a few improvements, but may need some more testing..

**Comment by dwhly** [comment]
Thanks!

**Comment by tilgovi** [comment]
Let's roll it out and find out :).

**Comment by ikreymer** [comment]
ok, go for it! I'll be ready for new issues :)

**Comment by ikreymer** [comment]
In the future, I should probably do a pull request to master, so you can merge when you deploy

**Comment by ikreymer** [comment]
Has it been deployed? Looks like it still not working, so maybe some other issue...

**Comment by tilgovi** [comment]
Yes

**Comment by ikreymer** [comment]
Looks like this still doesn't work on via, but does work on heroku.. My guess is it must be some other headers that via is sending from the proxy that mess it up?

http://pywb-h.herokuapp.com/https://www.edsurge.com/n/2015-06-23-tom-vander-ark-why-private-capital-wins-out-over-philanthropic-capital-in-the-game-of-innovation

**Comment by nickstenning** [comment]
Not sure what changed here but this now works fine.
