### ISSUE TITLE
Create HTML testing spreadsheet

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#20]
Move the [Google doc of HTML proxying test URLs](https://docs.google.com/document/d/15ngwKS1EoDVZE1JRDHLG3N0Y-XeCjCnxR9HhVASzrhA/) into a Google spreadsheet. The spreadsheet should have these columns:

* Test URL, plain version (hyperlink)
* Test URL, proxied version (this should be a hyperlink to the test page, proxied through the experimental HTML rewriter)
* Has this URL been tested with the experimental rewriter? (Yes/no)
* Were any problems discovered with proxying this URL? (Yes/no)
* What problems are there with proxying this URL? (Notes)
* Have all the problems with proxying this URL been resolved in the experimental rewriter? (Yes/no)

**Comment by jon-betts** [comment]
This has been replaced with: https://github.com/hypothesis/via3/issues/147
