### ISSUE TITLE
Video embeds seem to cause sidebar slow down

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/via#21]
Testing this URL:
https://via.hypothes.is/http://www.corestandards.org/Math/Practice/MP8/

It takes quite awhile for the sidebar to show (especially in Chrome), and even longer for the "Loading" text to go away from the search bar (again...especially in Chrome).

The only thing in the log were references to two video embeds (Vimeo URLs) and a couple lines where their output from `vidrw.js`.

I'm not sure that's the cause, but otherwise the page seemed "harmless."

Also, this came in via our support@ channel.

**Comment by tilgovi** [comment]
This might just be a symptom of that box being overloaded. We're in the process of fixing this right now. When I look at my network tab I see that some requests to via hang for a while. It seems intermittently slow.

**Comment by tilgovi** [comment]
I don't see any evidence that this has anything to do with the video embed so I'm going to close this.
