### ISSUE TITLE
Investigate New Relic NGINX integration for Via 3

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#21]
Investigate whether it would be worth deploying [New Relic's NGINX integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration) for Via 3. And if it is worthwhile, then deploy it.

A big part of what Via 3 does is just proxying files through NGINX, so it's important to know how Via 3's NGINX is performing in production. For example, maybe our NGINX config is suboptimal, or the choice of virtual hardware that we have NGINX running on. We might want some alerting. Etc.

-------------

This spike came to no conclusion. I was not able to install the agent sucessfully, so I can't say whether it's any good. 

I can say that I could not accomplish it in the time taken. Someone familiar with Elastic Beanstalk and New Relic would likely come to a different conclusion.

**Comment by jon-betts** [comment]
The NGINX plugin for New Relic requires "Infrastructure Pro" as per: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration

@ajpeddakotla is going to take a look at what we need to do to get an upgrade.

**Comment by jon-betts** [comment]
I've looked at this and honestly, I can't work out what we're supposed to do to get this working.

The basic overview is (https://newrelic.com/integrations/nginx-integration):

 * Install the agent
 * Install the integration
 * Profit

I'm failing to see how to do all three right now.

### The agent

The documentation (https://docs.newrelic.com/docs/infrastructure/install-configure-manage-infrastructure) provides different methods of agent installation for:

* Linux
* Docker
* Elastic Beanstalk

We are all three. 

The **Linux** one seems to be for hosts, which we aren't (or are we?)

The **Docker** one comes in two different flavous from what I can see:

* https://docs.newrelic.com/docs/infrastructure/install-configure-manage-infrastructure/docker-installation/docker-instrumentation-infrastructure - This says if you have an agent installed you don't have to do anything, but I think this only gets you container level metrics, and doesn't count for the purposes of NGINX
 * https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/data-instrumentation/monitor-containers-underlying-hosts-coreos - This is a docker container which _is_ an agent I think, and attempts to monitor the host and other containers, and requires various extra permissions and special setup to do it. This would _presumably_ also count as having the agent in the docker container and so might work?

The **Elastic Beanstalk** one (https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/installation/install-infrastructure-agent-aws-elastic-beanstalk) looks the easiest to install, and would seem to add the agent to the VMs we deploy which run docker. This would get us CPU and memory stats and so forth, but I've no idea if this counts as an "agent" for the purpose of getting NGINX monitoring running.

### NGINX integration

The installation for NGINX monitoring (https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration) states:

> If NGINX is not running on Kubernetes or Amazon ECS, you must have the New Relic Infrastructure agent installed on a Linux OS host that's running NGINX.

We aren't running Kubetnetes or Amazon ECS, and the host isn't running NGINX (it's running docker that runs NGINX). Is that good enough? Looking inside the tarball I don't think so. It seems the NGINX integration expects to be on the same host running the agent. _It really looks like they don't expect you to be running things in containers, or at least they are muddling host/container_.

Other forum posts online suggest both:

 * Installing the client directly in the docker container - Alpine isn't supported, so we'd have to build it from a tar ball, which is provided (sometimes) but not supported by New Relic.
 * That the above doesn't work and you have to use the "docker integration" mentioned in the agent section above - This seems to require you to be based on their image, not your own

I've had a quick look at the docker container they provide (https://hub.docker.com/layers/newrelic/infrastructure/latest/images/sha256-ad00adcc0c9fd691ba78f7d3c581dd6f7d5757f074eb43896fb8331299a4e68b?context=explore) and there are some flags in there to let the agent know it's in a container `ENV NRIA_IS_CONTAINERIZED=true` so maybe we can reverse engineer it into Alpine ourselves.

Assuming you find a way through all of that you now need to install NGINX with the New Relic plugin. As Alpine isn't supported, we'd have to:

* Find and download the right tarball from this list: https://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/
* Follow the instructions here (https://docs.newrelic.com/docs/integrations/host-integrations/installation/install-host-integrations-built-new-relic#tarball) to install it.
* It doesn't seem too bad (the tarball has like 4 things in it), but it definitely expects the agent to be installed

Only at this point would we know if any of this was right.

### Even if this worked do we even get what we want?

The New Relic page mentions the status we can expect to get from this:

 * https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#metrics

And basically its the same stats as you get from the stub monitoring extension: https://nginx.org/en/docs/http/ngx_http_stub_status_module.html

Which look like this:

```
Active connections: 291 
server accepts handled requests
 16630948 16630948 31070465 
Reading: 6 Writing: 179 Waiting: 106 
```

What that doesn't give us is the status codes, or any breakdown by URL etc. According to New Relic the same is true for NGINX Plus.

Interestingly this is contradicted here by NGINX: https://www.nginx.com/blog/nginx-plugin-for-new-relic/, which shows NGINX Plus reporting a great deal more besides, which makes me think that this NGINX New Relic plugin _might be something totally different_.

### NGINX incorporated to the rescue, kind of, but not really?

So according to the above NGINX plugin page (from NGINX, not New Relic) there is (maybe) a different plugin provided by NGINX itself. Unfortunately the entire docs for it on the website are now:

> You can download the latest integration plug‑in for New Relic and NGINX from
https://github.com/nginxinc/new-relic-agent.
> 
> NGINX, Inc. no longer provides free support for this plug‑in.
>
> Please refer to https://www.nginx.com/products/pricing/ for commercial support options.

Going to that github page however has instructions for deb packages and RPMs (Alpine is Debian based I think, so maybe that might work).

Of note about this:

 * It looks like we get no support (that might be fine for a while?)
 * It _doesn't_ seem to require an Infrastructure Pro licence from New Relic or anything else
 * It _doesn't_ mention requiring the New Relic agent (it refers to itself as both a New Relic agent and plugin)

My guess is this is something standalone.

I have no idea if it does anything, but I can confirm you can build the Debian package from it pretty easily under Ubuntu.

**Comment by jon-betts** [comment]
Ok, so with that nice rant out of the way: **what do?**

### New Relic

I don't know what I'm supposed to do with New Relic's provided tools, and if they want our money I think they should explain it to us. If they can't, or won't then I don't think it's worth pursuing.

The New Relic Elastic Beanstalk integration looks interesting to get general host statistics, but that isn't what this ticket was about, and we shouldn't try and work backwards to a reason to give our money away.

### NGINX

The NGINX provided plugin has the great benefit of being one thing to try and seems to do most everything we'd get from the above, and for free as well, so it might be worth trying.

It won't get us host stats though. On the other hand we've managed until now with not having this for _anything_ so I don't know if that's a big deal.

It also looks unsupported, so if we can't get it working, or it stops working we are on our own without forking over some cash to NGINX. _Note!_ If we did fork over some cash and get NGINX plus, the output looks absolutely rad and has all the status codes etc.

### DIY

None of the above actually solves all of the problems we were trying to solve. We still won't know if NGINX is up and happy, but serving 500's to everyone. We can probably get decent coverage for:

 * Is it dead? - By adding pingdom routes that check the NGINX portion of Via 3 separately from the Python part
 * Is it happy? - By stopping NGINX from proxying 50x errors and such from external services, so that all 50x errors are coming from NGINX itself. Papertrail could then alert when we get a lot of these in a row

**Comment by jon-betts** [comment]
I've got a response from the New Relic support people. Which sent me this:

 * https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery

It seems you can install an agent on the host (VM in our case?) which can automatically discover the NGINX container.

I haven't dug into it but I think this means:

 * We can configure NGINX to expose stats, but otherwise leave it be
 * Install the monitoring on the host above
 * Add the right config, and these should play together

**Comment by jon-betts** [comment]
I've done something here: https://github.com/hypothesis/deployment/pull/94

It doesn't seem to do anything. I'm kind of feeling instead of getting everyone who knows about the various things to tell me about them, it might be useful to get someone who knows anything about this to take over.

I'm just getting snippets I can't understand and making changes I can't verify or trust. It's classic flail until something works, and it's dangerous.

I've backed out that PR above. It wasn't even in the right product: https://github.com/hypothesis/deployment/pull/95/files

**Comment by jon-betts** [comment]
So the infrastructure agent is installed and reporting things back. It's not super helpful yet as it isn't integrated with NGINX, but it can see the docker container running.

Currently everything has random names as well. Next steps:

 * Get NGINX to expose stats: https://github.com/hypothesis/via3/pull/164
 * Get the New Relic agent to collect them: https://github.com/hypothesis/deployment/pull/97/files
 * Stop things from having totally goofy names - The above may fix this?
 * Put it live if it works

**Comment by jon-betts** [comment]
Ok, so we've got the stats end-point and I've tried to configure monitoring. But I've just noticed we've lost all regular NewRelic python end-point monitoring in QA since last Friday. Why? I don't know, but it seems likely to be related to this.

There's a PR to back it all out: https://github.com/hypothesis/deployment/pull/98

**Comment by jon-betts** [comment]
I've tried a bunch of things since this last comment. The last attempt was:

 * https://github.com/hypothesis/deployment/blob/4bd5959e05c4f673881b153362607d4768250055/via3/ebextensions/qa/newrelic.config

This didn't enable logging as I thought it would. There's nothing special about this as a point to stop, but it makes any further changes 100% guesswork. I've spent a spent far to long on this already and I have no estimate for whether I'm nearly there or miles away.

The aim of the spike was to find out whether it's worth installing the New Relic NGINX solution. Unfortunately I'm unable to provide an answer on that.

**Comment by jon-betts** [comment]
I'm going to summarise what I _think_ you are supposed to do, with the caveat this doesn't work.

Best to refer to this to see what I'm talking about: https://github.com/hypothesis/deployment/blob/4bd5959e05c4f673881b153362607d4768250055/via3/ebextensions/qa/newrelic.config

* Create a file called '.ebextensions/newrelic.config' as described here: https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/installation/install-infrastructure-agent-aws-elastic-beanstalk
 * This file needs to create two files:
   * One to configure the infrastructure agent running on the host
   * Another which configures the nginx "integration" which you need to tell how to discover the 
NGINX instance
 * Change that file to: 
   * Also install the `nri-nginx` package
   * Add configuration for "discovering" the NGINX instance and report back
 * The two parts here are called the "Infrastructure Agent" and the "Integration"

## Notes on discovery:
 
 * It seems the infrastructure agent is aware of docker containers by default, but you need to tell it that one is NGINX to have it monitor it
 * Our docker images retain no metadata I can see that tells you where they came from. Their image names are just hexadecimal
 * The only thing I thought might work is the port
 * Some incomplete overview here: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config
 * An example file that happens to include NGINX and more on discovery here: https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
 * A tarball containing the content which gets installed with 'nri-nginx': https://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/nri-nginx_linux_2.0.1_amd64.tar.gz
 * When the docs say "the example file" I think they mean from the tarball above, which is also the content I think you get via `apt-get install nri-nginx`
 * I never got this to work

## How does this show up in New Relic?

 * I think it's supposed to show up in `INFRASTRUCTURE > Third-party services` separate from the app reporting
 * The docker integration appears to activate automatically with the install of the EB agent
 * The NGINX one never did show up, so I don't know what it looks like

The infrastructure integration appears to smear EB data across multiple products. All the hosts have incomprehensible hex names (as they do in real life). You can then drill down into them to see hosts which again, have opaque ip based names from AWS. Finally you can see the docker containers which have random docker names. There are a decent collection of stats for them all at the level of memory, load and CPU.

I did manage to tag some of this as being an "Application" with a name. This seems to a filter you can apply to hosts. It seems to be loosely tied to the via 3 app reporting in some way. The settings call this the "host name" but it appears as "Application" in the interface. The host names are still the ones from AWS.

The docker overview here is a big collection of graphs for every docker container you have (all with randomly generated names in our case). You can toggle them on and off, but you don't seem to be able to follow them back to the application they are a part of. Perhaps you are supposed to create your own dashboards to make sense of it?

This was working for a while, but currently has no data. I don't know why.

## Logging in Linux

It seems logging is off by default in Linux, and if you want to rotate it, you have to do it yourself.

I tried enabling it as described here: https://docs.newrelic.com/docs/infrastructure/install-configure-manage-infrastructure/configuration/infrastructure-configuration-settings. No effect.

The agent makes a directory in `/var/log`, but it's empty. There are also files in `/var/new-relic-agent/logs` or something similar which look like example files to configure various kinds of logging. I didn't see a mention of these in the docs. These come from installing the `nri-nginx` package.

## Other discoveries

 * AWS has some monitoring of HTTP codes grouped by 4xx or 5xx etc. This is what we are after, and actually wouldn't be provided by this even if it works. Could be worth a look
 * Enabling stats output in NGINX is trivial, but it's a good idea to lock down
 * For this, we ended up with an idea to generate a hash file on the fly when it's deployed from the password in EB. It then becomes arbitrary, easy to change and doesn't need to be written down anywhere

## Final summary

Would not recommend to a friend

**Comment by robertknight** [comment]
Looking at `/var/log/messages` (either via SSH or by requesting "Full Logs" from the Elastic Beanstalk console) I found the following:

```
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": CREATE" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": MODIFY" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": MODIFY" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": MODIFY" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": MODIFY|ATTRIB" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": MODIFY|ATTRIB" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": MODIFY|ATTRIB" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
May 18 17:23:27 ip-10-1-3-57 newrelic-infra: time="2020-05-18T17:23:27Z" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.Manager error="yaml: line 1: mapping values are not allowed in this context" event="\"/etc/newrelic-infra/integrations.d/nginx-config.yml\": MODIFY|ATTRIB" file_name=/etc/newrelic-infra/integrations.d/nginx-config.yml function=handleFileEvent
```

Looking at the linked config (https://github.com/hypothesis/deployment/blob/4bd5959e05c4f673881b153362607d4768250055/via3/ebextensions/qa/newrelic.config) and comparing to the sample at https://github.com/newrelic/nri-nginx/blob/master/nginx-config.yml.sample I notice an extra layer of indentation on the line that begins `discovery:`. Pasting the YAML config into an online syntax checker reports the above error shown in the logs and removing the indentation fixes the error. This could possibly explain why the nginx integration failed to show up.

> Our docker images retain no metadata I can see that tells you where they came from. Their image names are just hexadecimal

Poking at the image on via3-qa using `docker image inspect <ID>` it looks to me like the Elastic Beanstalk deploy is creating a new Docker image which extends/inherits from the one we publish to Docker Hub as part of the build process. The one we publish will have a name such as `hypothesis/via3:20200519-g433e495` but image that actually gets run is a "child" of that image whose tag is `aws_beanstalk/current-app:latest`.

Matching on ports is a reasonable thing to do, but I think matching `aws_beanstalk/current-app` would also have worked here. Alternatively you can add arbitrary custom attributes via the `LABEL` command in the Dockerfile.
