### ISSUE TITLE
Investigate short term solutions to via monitoring 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/via#213]
### Problem 
Currently, as we build the new version of via, we've still got the problem of legacy via falling over when we have high loads. We essentially lack the monitoring into legacy via and need to address this so that we can ensure usability and reliability of via during peak hours. 

The follow up actions written below came out of a call with @seanh @hmstepanek @robertknight @dmfine and @dwhly. 

### Potential follow up actions
(We may not need to do all of these) 
- [ ] Check whether extended Via downtime will result in PagerDuty alerts
- [x] Migrate blocklist from Cloudflare to Via (In progress - @robertknight) 
- [x] ~~See if alerting rules can be configured on time of day.~~ (_Deferred for the time being - @robertknight_)
- [x] Throw more resources at it. What is the cost of this? There is no autoscaling on via currently. How much would it cost to double/triple the number of servers. Peg it to 10 or 20 servers. Each micro instance is $7/month. We might need to move the environment to a new platform version (Rob ran into this problem recently). @dmfine is going to look into this and take immediate action on it.

**Comment by ajpeddakotla** [comment]
A couple of other things have come up 
- Via deploys now take a very long time w/ the # of instances now increased. Rolling updates may be needed. See discussion in Slack: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1579621988085400
- PR open to turn off some of via's rewriting. Might be worth reviving that PR and deploying it piecemeal. @robertknight can you link the PR here?

**Comment by robertknight** [comment]
I think we can close this out provided that we've met this criteria:

> - Check whether extended Via downtime will result in PagerDuty alerts

Do our current alerts cover this or not?

**Comment by dmfine** [comment]
We have three pagerduty alerts set:
EB cluster health SEVERE
EB cluster network out under threshold
Cumulative throughput under 50rps
This should catch a wide range of major problems. Attempts to notify on high request latency generated false alerts because VIA's latency is affected by the sites which it is proxying. We turned that alert off.
