### ISSUE TITLE
Block access to the same addresses as original Via

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#218]
In Via we use Squid to block outbound traffic to dangerous locations, for example to end-points which might divulge AWS secrets exposed within the container for configuration:

* https://github.com/hypothesis/via/blob/master/conf/squid.conf

We need a similar system to block access in Via 3's HTML component.

It seems like a bit of overkill to have Squid there just for that. I think an `iptables` config would do the job, but I don't really know how to do that, and it's probably a bad thing to guess at.

## Testing notes

* You can go to Via 3 in QA and enter any URL for test at: https://qa-via3.hypothes.is/

### Some good URLs

* https://qa-via3.hypothes.is/route?url=http%3A%2F%2Fexample.com
* https://qa-via3.hypothes.is/route?url=https%3A%2F%2Fexample.com
* https://qa-via3.hypothes.is/route?url=https%3A%2F%2Fh.readthedocs.io%2F_%2Fdownloads%2Fen%2Flatest%2Fpdf%2F

### Non standard ports

* https://qa-via3.hypothes.is/route?url=http%3A%2F%2Fwww.asnt.org%3A8080%2FTest.html

### A bad config URL

* The following should be blocked: https://qa-via3.hypothes.is/route?url=+http%3A%2F%2F169.254.169.254%2Flatest%2Fmeta-data%2F
* However it's already caught by Cloudflare, so we can't know

**Comment by indigobravo** [comment]
A branch has been pushed for approval: https://github.com/hypothesis/deployment/pull/105

**Comment by indigobravo** [comment]
I hate to be the bearer of bad news, but the requested functionality is proving very difficult if not impossible to guarantee automation in all conditions with our Elastic Beanstalk Docker implementation and `iptables`. The fundamental problem relates to the internal usage of IP ranges that we are looking to block the application running inside Docker from accessing. I have been able to manually configure a solution that appears to work on VIA3 QA. However, I suspect there may be unexpected problems we are yet to realise. 

The manual solution blocks the unwanted IP and Port access. However, when it comes to providing an automated means to implement this over and over again the solution falls down. This problem specifically relates to the `docker0` network deployed by elastic beanstalk which we have little influence over, and the manner in which IP addresses are allocated within the 172.16.0.0/12 subnet we are looking to block. During my manual configuration I can check the IP that has been allocated. However, through the automation of an `ebextension` I do not have access to this information. I can make a **good** guess, but it will not be a reliable implementation.

I think implementing at the `network layer` is a no go, and we are going to have to provide a solution within the `application layer` using some kind of HTTP proxy.

I do have a couple of other ideas if we want to continue researching a solution outside of the application, but I think we should discuss these with an understanding of how complex implementing proxy would be.

I hope this all makes sense. Let me know if you would like any further detail.

For now, I will proceed with the closure of this issue.

**Comment by robertknight** [comment]
To add to the above, my understanding from a Slack discussion is that the problem with the iptables configuration is that when a process in the container makes a DNS or HTTP request (and perhaps other things), the response packet gets blocked before it reaches the container.

**Comment by jon-betts** [comment]
Excuse the dumb question, but if we can list the things we want to block with Squid, can't we use a similar static list for IP tables within the container?

**Comment by indigobravo** [comment]
Quick update - I am making progress here and believe a workable solution is in the making. I have created an internal issue to track my work: https://github.com/hypothesis/playbook/issues/342

**Comment by jon-betts** [comment]
A real quick recap of our discussions about blocking ports:

 * The main thing this is here to solve is accessing bad hosts (like localhost), not any particular port
 * We don't think the inclusion of port blocking was intentional in Squid, it's probably just copy paste from an example config
 * Blocking wide port ranges to match the Squid config has a performance cost in iptables
 * There's no attack you can do to us in port X you can't do on port 80, or 443

The summary is we don't think there's any advantage to blocking outbound ports which we make HTTP requests on. It also runs the risk of breaking sites. Therefore the port blocking part has been removed completely.

**Comment by indigobravo** [comment]
A solution has been deployed. Closing this ticket. Please let me know if you have any further questions.
