### ISSUE TITLE
Setup error when make dev is executed.

### ISSUE THREAD

**Issue by CArandzAlegre** [hypothesis/via#220]
Hi! Good day!

I got this error after I clone the repo and run the make dev command.

./bin/install-python: 38: pyenv: not found
./bin/install-python: 41: pyenv: not found
./bin/install-python: 43: pyenv: not found
./bin/install-python: 43: /versions/2.7.16/bin/pip: not found
./bin/install-python: 38: pyenv: not found
./bin/install-python: 41: pyenv: not found
./bin/install-python: 43: pyenv: not found
./bin/install-python: 43: /versions/3.6.9/bin/pip: not found
make: *** [Makefile:56: python] Error 127

NOTE: I check the path and pip is there.
![Screenshot from 2020-02-18 19-22-33](https://user-images.githubusercontent.com/37786991/74731933-133ac200-5284-11ea-85c4-343b63b1f334.png)

Also how can I run this locally? or the command line way.
Thanks for the help. :)

**Comment by robertknight** [comment]
Hello. You need to install [pyenv](https://github.com/pyenv/pyenv) to run any of Hypothesis's Python projects. The documentation for the [Hypothesis server](https://h.readthedocs.io/en/latest/developing/install/#you-will-need) explains the common set of tools (Git, Docker, Node, pyenv) that are needed to work with most Hypothesis projects.

**Comment by CArandzAlegre** [comment]
@robertknight yup I already have pyenv in my local VM machine.
![Screenshot from 2020-02-18 19-51-52](https://user-images.githubusercontent.com/37786991/74733842-264f9100-5288-11ea-889d-05b1a206c36b.png)

**Comment by CArandzAlegre** [comment]
@robertknight why did you close the reported issue when in fact it is not resolved yet. Any feedback?

**Comment by robertknight** [comment]
From your initial report it seemed obvious that pyenv was not installed. I was wrong about that. Can you run either of the following commands on their own:

1. `make python`
2. `bin/install-python`

**Comment by CArandzAlegre** [comment]
![Screenshot from 2020-02-18 20-18-04](https://user-images.githubusercontent.com/37786991/74797513-3c9c3200-5306-11ea-9bf5-8a9c103d0b90.png)

**Comment by CArandzAlegre** [comment]
Hi @robertknight Its now working. The only issue is the PATH. Thank you!
