### ISSUE TITLE
Visiting /<URL> with an invalid URL crashes Pyramid

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#23]
If you ask Via 3 to proxy an invalid URL (for example just visit <https://qa-via3.hypothes.is/foo> on QA, or <http://localhost:9082/foo> in dev) then [this call to `requests.get()`](https://github.com/hypothesis/py-proxy/blob/9b1973c7a7fd53b46880a01f63a1ba803c2bb528/py_proxy/views.py#L56) crashes with `requests.exceptions.MissingSchema`. Other types of URL might raise other types of error.

In general if the `requests.get()` raises for any reason, even with a valid URL, (for example if there's a network error), it'll crash. We need to catch all exceptions that `requests.get()` could raise and handle them appropriately.

An appropriate response might be to show the user an error page explaining what went wrong with the external request, but don't crash and don't report anything to Sentry. The failed external request _should_ be logged to Papertrail, though.

Sentry Issue: [VIA3-1](https://sentry.io/organizations/hypothesis/issues/1446196461/?referrer=github_integration)

```
HTTPNotFound: The resource could not be found.
  File "pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound

MissingSchema: Invalid URL 'foo': No schema supplied. Perhaps you meant http://foo?
(24 additional frame(s) were not displayed)
...
  File "requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
```

**Comment by jon-betts** [comment]
Fixed in a basic way in Content type error catching #65
