### ISSUE TITLE
Get Via HTML deployed to live

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#234]
This ticket will:

 * Plan the DNS names and numbers of machines used to deploy
 * Add / create CI pipelines to ensure the code is deployed
 * Get the product in QA and Live
 * ... behind Cloudflare

###  Implementation notes

* https://github.com/hypothesis/playbook/blob/master/docs/deploying-a-new-app.md

**Comment by indigobravo** [comment]
Due to be working on this the week starting: 2020-09-07

**Comment by jon-betts** [comment]
I _think_ the relevant stuff has been updated / nicked from Via 3 to make this work in: https://github.com/hypothesis/viahtml/pull/2

I could have missed something of course.

**Comment by indigobravo** [comment]
Starting deployment work. Updates to follow.

**Comment by indigobravo** [comment]
The deployment work is basically complete here. However, there are updates that need to be made to the application before it will be able to fully function. We have a slack thread that provides more information: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1600701889007900

Further updates may be required once the application has been updated. These may include:

* Confirming the git repo pushes commits to jenkins correctly.
* Monitoring, which is being dealt with in another ticket: https://github.com/hypothesis/via3/issues/246
