### ISSUE TITLE
JS type errors seen at https://via.hypothes.is/http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2695392/#

### ISSUE THREAD

**Issue by judell** [hypothesis/via#25]
Console JS error:

![image](https://cloud.githubusercontent.com/assets/46509/8839098/13fbf232-3087-11e5-9f96-502ffa2e2701.png)

**Comment by ikreymer** [comment]
hm, which browser is this? I don't see this in either Chrome or FF

**Comment by judell** [comment]
Oops, sorry. That's Safari.

**Comment by ikreymer** [comment]
This may be fixed now, no longer see these in Safari, and the annotator bar is loading, though there are a couple other JS errors.
