### ISSUE TITLE
Don't let Via annotate Via

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/via#29]
Looks like Via went down today *possibly* because someone (a friend, actually) tried to past a Via URL into the home page and annotate it ('cause they wanted to annotate/reply to my annotations! I have smart friends. :wink:).

However, it looks like Via may have tried to archive itself...

Not positive on that, but it was up before he tried, and down immediate after that.

This sounds like a job for, @hypothesis/site-reliability!

**Comment by tilgovi** [comment]
Indeed. Seems to kill it.

**Comment by ikreymer** [comment]
Curious, are there any errors in the log? Or just hang?
http://pywb-h.herokuapp.com/pywb-h.herokuapp.com/ seems to work.

Btw looking at uwsg.ini I noticed that its not running with gevent workers but with 10 processes by default, probably should be gevent instead?

**Comment by ikreymer** [comment]
Even though pywb supports recursively loading itself, I'm guessing we want to guard against it in via :)

**Comment by tilgovi** [comment]
Oh, it isn't running with gevent. I just pushed a commit to make everything go through ./run-uwsgi and have the gevent settings there.

**Comment by ikreymer** [comment]
Ah, i see now. Forgot about `run-uwsgi.sh`

**Comment by judell** [comment]
Related: https://github.com/hypothesis/h/pull/2378

**Comment by nickstenning** [comment]
I'm going to close this. You can still load up via pages in via but it seems not to crash anything.
