### ISSUE TITLE
Implement Nginx response status handling

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#29]
When Nginx proxies a PDF or static file for us (the `/proxy/static/<URL>` endpoint), what should the HTTP statuses of Nginx's responses be?

I'm guessing the current situation is that Nginx proxies the status code from the third-party. So if the URL being proxied returns a 500, Nginx will return a 500, and so on.

This probably isn't what we want because these HTTP statuses will pollute our monitoring. We probably want to 5xx's and other unsuccessful status code for actual problems with our service (e.g. Nginx crashed).

This card is to decide what status codes we want Nginx to respond with, depending on the different status codes that the proxied URL might respond with. And then to implement that.

**Comment by jon-betts** [comment]
Yep it just barfs back whatever it receives from the other side:

 * http://localhost:9083/proxy/static/http://httpbin.org/status/500
 * http://localhost:9083/proxy/static/http://httpbin.org/status/561 - Made up code

It looks like come combination of:

 * `proxy_intercept_errors` - http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors
* And `error_page` - http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page

Could do the trick

**Comment by jon-betts** [comment]
Done!
