### ISSUE TITLE
Implement appropriate caching for the root endpoint

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#30]
The app's root endpoint (`/<THIRD_PARTY_URL>`) make a get request to the given `THIRD_PARTY_URL` but only downloads the response headers in order to decide whether the URL is a PDF or not, and then returns a redirect to either the HTML or the PDF proxying endpoints.

It should be possible to cache these redirect responses from the root endpoint, at least in the user's browser and possibly also in Cloudflare. But it's not trivial. For example:

* How long do we want to cache the responses for? (Probably not for too long since the response at `THIRD_PARTY_URL` might change and that might change what our redirect response would be.)
* When should we cache the response and when not? For example if `THIRD_PARTY_URL` returns a 4xx or 5xx error we probably don't want to cache our decision (PDF or not?) at all. On the other hand if it's a 2xx we may want to cache our PDF-or-not decision for a time.

# The goal

## Current behavior

 * We return no headers relating to caching for the root
 * Cloudflare does not attempt to cache: `CF-Cache-Status: BYPASS`
 * Every call comes direct to our sevice and the user waits
 * The first call takes ~800ms on my machine

## Desired behavior

 * Errors should not be marked for any kind of caching
 * Once a suitable period of timeout for successful PDF proxying has been chosen (in https://github.com/hypothesis/py-proxy/issues/31) we should probably match that when we are redirecting to PDFs
 * Users should not return to us during this time
 * Once the time-limit has expired, the content should be served to the user immediately while we check the validity asynchronously

# How can this be achieved?

 * When things go well we set cache `Cache-Control` headers to prompt caching
 * We set `Cache-Control: public max-age=<short> stale-while-revalidate=<long>`
    * `public` - Tells Cloudflare to cache
    * `max-age=<short>` - Keeps a short leash so if the underlying resource changes we'll notice
    * `stale-while-revalidate=<long>` - Tells Cloudflare to serve the contents it's got and then recheck with us asynchornously 
 * Cloudflare will need to be configured to pass on the headers we send
   * It isn't setup like this now, and it not trivial to do so
   * This is because we are using all of our page rules to block bad content from old via (porn and advertising etc)
   * We'll have to experiment to see what happens in this context

**Comment by jon-betts** [comment]
View caching was implemented in: https://github.com/hypothesis/via3/pull/53

Parts of it were also rolled back as a result of: https://github.com/hypothesis/via3/pull/77
