### ISSUE TITLE
Implement appropriate caching for the /proxy/static/ endpoint

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#31]
The `/proxy/static/<THIRD_PARTY_URL>` endpoint is currently used to proxy third-party PDFs. In future it'll also be used to proxy other kinds of files (resources from HTML pages).

It should be possible to cache these responses from the `/proxy/static/` endpoint, at least in the user's browser and possibly also in Cloudflare. But it's not trivial. For example:

* How long do we want to cache the responses for? (Probably not for too long since the response at `THIRD_PARTY_URL` might change and that might change what our redirect response would be.)
* When should we cache the response and when not? For example if `THIRD_PARTY_URL` returns a 4xx or 5xx error we probably don't want to cache our response at all. On the other hand if it's a 2xx we may want to cache it.

# The goal

## Current behavior

 * If a PDF sets a "Cache-control max-age" this is used by Cloudflare:
   * `Cache-control max-age=864000`
   * http://pdf995.com/samples/pdf.pdf
   * https://via3.hypothes.is/proxy/static/http://pdf995.com/samples/pdf.pdf
 * If the PDF has no "Cache-control" Cloudflare defaults kick in
   * https://www.vmware.com/pdf/ws6_manual.pdf
   * https://via3.hypothes.is/proxy/static/https://www.vmware.com/pdf/ws6_manual.pdf
   * The default seems to be 14000
* If an error occurs, Cloudflare defaults should kick in:
    * https://support.cloudflare.com/hc/en-us/articles/200172516-Which-file-extensions-does-CloudFlare-cache-for-static-content-#h_51422705-42d0-450d-8eb1-5321dcadb5bc
   * 404, 410 - 3m
   * 405, 414, 501 - 1m

## Desired behavior

 * We probably want an Expires header of our own choosing regardless of the source (**do we?**)
 * This will give us control at the app level of how long things get cached for regardless of the source preferences
 * Do we want to enable GZip? Some PDFs are compressed, but not all

# How to do this?

 * [This tutorial](https://www.digitalocean.com/community/tutorials/how-to-implement-browser-caching-with-nginx-s-header-module-on-ubuntu-16-04) demonstrates different expiry for different mime types in NGINX
   * For example `html=off, pdf=whatever`
   * May require `headers more`... which we already have?
 * [The ngx_http_headers_module docs](https://nginx.org/en/docs/http/ngx_http_headers_module.html) describe that Expires and friends only apply to 200, 201 (1.3.10), 204, 206, 301, 302, 303, 304, 307 (1.1.16, 1.0.13), or 308 (1.13.0)
 * Due to our Cloudflare setup, whatever we do is probably going to get defaulted to 4 hours if we enable caching at all

# Background

 * http://pdf995.com/samples/pdf.pdf [via](https://via3.hypothes.is/proxy/static/http://pdf995.com/samples/pdf.pdf) - Example pdf with Expires
 * https://www.vmware.com/pdf/ws6_manual.pdf [via](https://via3.hypothes.is/proxy/static/https://www.vmware.com/pdf/ws6_manual.pdf)- Example pdf without Expires

**Comment by jon-betts** [comment]
Implemented in https://github.com/hypothesis/via3/pull/76
