### ISSUE TITLE
Annotations missing for https://via.hypothes.is/http://www.theawl.com/2015/07/in-no-charts

### ISSUE THREAD

**Issue by judell** [hypothesis/via#31]
Annotations on http://www.theawl.com/2015/07/in-no-charts are visible in the extension, not using via, and there is no obvious console error to suggest why not.

**Comment by tilgovi** [comment]
For me, annotations are visible and there are copious error messages. Chrome deals much better with these than Firefox, the latter of which is rendered unusably slow by the issues.

**Comment by tilgovi** [comment]
For instance: 

```
DOMException: Blocked a frame with origin "https://via.hypothes.is" from accessing a cross-origin frame.
    at Error (native)
    at init_iframe_wombat (https://via.hypothes.is/static/__pywb/wombat.js:1690:48)
    at HTMLIFrameElement.getter [as contentWindow] (https://via.hypothes.is/static/__pywb/wombat.js:1293:13)
    at i (https://via.hypothes.is/js_///platform.twitter.com/widgets.js:3:26285)
    at https://via.hypothes.is/js_///platform.twitter.com/widgets.js:2:10143
    at i._invoke (https://via.hypothes.is/js_///platform.twitter.com/widgets.js:1:19170)
    at i._processRequest (https://via.hypothes.is/js_///platform.twitter.com/widgets.js:1:19494)
    at https://via.hypothes.is/js_///platform.twitter.com/widgets.js:1:19949
    at Array.map (native)
    at i.receive (https://via.hypothes.is/js_///platform.twitter.com/widgets.js:1:19924)
```

**Comment by tilgovi** [comment]
And then `Received message of type object from http://www.theawl.com, expected a string`.

**Comment by tilgovi** [comment]
The second of these errors seems to occur repeatedly, forever, at a very high rate. It's possible this is what renders Firefox unusable.

Both of these are related to the facebook connect frame, I think. The pywb rewriter is perhaps messing with these too much, causing problems with postMessage, causing security issues when it tries to set `document.domain`, etc, etc.

**Comment by ikreymer** [comment]
Hmm, yeah i think its something with postMessage().. the original site actually has a bunch of errors also, though they don't repeat.

**Comment by ikreymer** [comment]
Try now at: http://pywb-h.herokuapp.com/http://www.theawl.com/2015/07/in-no-charts

Some fixes related to postMessage, seems to work both in Chrome and FF

**Comment by tilgovi** [comment]
Looks good here!

**Comment by judell** [comment]
Thanks Ilya.

Wow, that page is a beast.

**Comment by tilgovi** [comment]
Why did you close this?

**Comment by ikreymer** [comment]
at this point, this is ready to go, but not yet deployed. Just need to update via 0.10.5 -> 0.10.6

**Comment by judell** [comment]
Oops.

**Comment by tilgovi** [comment]
Done.

**Comment by ikreymer** [comment]
Hm, looks like https://via.hypothes.is/static/__pywb/wombat.js is still the older version.. maybe didn't get updated?

**Comment by ikreymer** [comment]
Oh nm, correct now :)
