### ISSUE TITLE
Implement appropriate caching for the /static/* endpoints

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#32]
We serve [the static files](https://github.com/hypothesis/py-proxy/tree/master/py_proxy/static) at `/static/*` endpoints. These should be cached in Cloudflare, if they aren't already in such as way as to reduce load on our service as much as possible without inconveniencing users during deploys.

# The goal

## Current (?) behavior

 * Content is served via Pyramid with `add_static_view`
 * `Last-Modified` header is automatically added
 * Cloudflare chooses to apply default timeouts (or we've overridden it)
 * This is 7200s/2h (according to docs), 14400s/4h (observed) for CSS, JS etc.
 * HTML is never cached
 * In order to check current-ness Cloudflare will have to call us at un-predicable times

## Desired behavior
 * Content is served via Pyramid with `add_static_view`
 * Content is served with the `Cache-Control max-age` of 31536000 (1 year and the max allowed)
 * Cloudflare will read the content once, and never bother us again
 * HTML is cached along with all other types of assets in the static directory
 * When the service is redeployed users see the new versions of files immediately

# How can this be achieved

## Outside of Pyramid?

* [Whitenoise](http://whitenoise.evans.io/en/stable/base.html) is a wrapper you put round your WSGI app
 * It sets various sensible headers, but has a very short Expires (60s)
 * Due to our Cloudflare setup, this should get defaulted to 4 hours anyway (needs testing)
 * This also has the benefit of skipping the Pyramid app completely

This is only going to get us so far, there's no attempt at things lasting forever here yet. It may also ultimately prove to be unneccessary.

## In Pyramid?

 * The central tension is between never being bothered again and users seeing new content
 * Blanket setting the `max-age` will achieve the first, but fail the second
 * The solution is to use a [cache buster](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/assets.html#cache-busting)
 * This will modify the URL when served via `request.static_url()`

## For this to work the following must be true:

 * All links to content must be served with `request.static_url()` or the cache busting is not applied
   * See `'py_proxy/templates/pdfjs_viewer.html.jinja2` for many examples of hard coded strings
 * Behavior in dev with restarting will need to be observed (does changing static content trigger a reload or do we need to disable cache busting locally?)
 * [Apparently we need to set the `Cache-control` `max-age` _and_ set it to `public`](https://support.cloudflare.com/hc/en-us/articles/200172516-Which-file-extensions-does-CloudFlare-cache-for-static-content-#h_51422705-42d0-450d-8eb1-5321dcadb5bc) for this to work with Cloudflare (Pyramid just sets the `max-age` without any type specified) 

----

Test URLs:

 * https://via3.hypothes.is/pdf/http://pdf995.com/samples/pdf.pdf - An example PDF proxied file
 * https://via3.hypothes.is/static/pdfjs-2/build/pdf.worker.js  - An example file (this looks very goofy when loaded separately for some reason)
 * http://0.0.0.0:9082/static/pdfjs-2/build/pdf.worker.js - The same file served locally

Background:
 * [Understanding Cloudflare's CDN](https://support.cloudflare.com/hc/en-us/articles/200172516-Which-file-extensions-does-CloudFlare-cache-for-static-content-) -  Default caching behavior for Cloudflare when you don't do anything special
 * [Pyramid cache busting](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/assets.html#cache-busting) - How to configure Pyramid to cache bust

**Comment by seanh** [comment]
I haven't used it before but I've heard good things about <http://whitenoise.evans.io/en/stable/>, might be worth a look to see whether it'd make implementing this easier

**Comment by jon-betts** [comment]
There's also a decent possibliity we aren't reading any HTML from that directory (in this case) as we copied it and made it the basis for our Jinja templates. As for whether we _should_ be completely re-rendering the HTML is a different business. Couldn't we just read a parameter with javascript?

**Comment by jon-betts** [comment]
Work for getting some level of caching and static file serving was done in: https://github.com/hypothesis/via3/pull/54

But has issues and was rolled back. It's being tried again in https://github.com/hypothesis/via3/pull/68

**Comment by jon-betts** [comment]
We now have caching working, but there are some effects of this:

 * I've setup a page rule to try and respect the origin cache control
 * The setting to just pass them through exactly does not appear, instead the minimum time is 30 minutes
 * We really shouldn't be setting any (or certainly any long) timeouts on HTML pages as it's impossible to tell the client to get new assets when they've moved

**Comment by jon-betts** [comment]
This is in place now. The how of it turned out nothing like the specified.

The default now is cache for 1 day and check back in 5 I think.

**Comment by jon-betts** [comment]
Immutable static content has for the most part been implemented. The result is that the /pdf/ HTML page takes about 600ms to load, but all the assets are very fast.
