### ISSUE TITLE
PLOSONE PDFs won't fetch w/ via

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#32]
Try this:

https://via.hypothes.is/http://www.plosone.org/article/fetchObject.action?uri=info:doi/10.1371/journal.pone.0131856&representation=PDF

**Comment by BigBlueHat** [comment]
However, this URL works just fine:
https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=http%3A%2F%2Fwww.plosone.org%2Farticle%2FfetchObject.action%3Furi%3Dinfo%3Adoi%2F10.1371%2Fjournal.pone.0131856%26representation%3DPDF

So...looks like we need to encode those URLs during redirect.
