### ISSUE TITLE
Astrophysics Data System search page isn't annotate-able

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/via#34]
https://via.hypothes.is/https://ui.adsabs.harvard.edu

Too much JS; not enough Web.

**Comment by BigBlueHat** [comment]
@judell not really sure this is the best place for these...thoughts? :thought_balloon:

**Comment by ikreymer** [comment]
It's good for me to see sites that are problematic.. so far many have been fixable. This should probably be fixable, as far as the live proxy, though not sure how the loading page will affect annotations anchoring..

**Comment by judell** [comment]
> It's good for me to see sites that are problematic.. so far many have
been fixable

It would be interesting to keep track of those that are not, and of why
they are not.

**Comment by ikreymer** [comment]
With time, they should all be fixable :)

With latest pywb, it should work with trailing slash (before there were other issues):
https://via.hypothes.is/https://ui.adsabs.harvard.edu/

Seems pretty good as far as home page..

**Comment by tilgovi** [comment]
We should redirect to the trailing slash when there is an empty path component, since the path is supposed to default to `/` in HTTP, and never be empty.

**Comment by BigBlueHat** [comment]
@tilgovi good call. @ikreymer thanks for being here. :smile:

**Comment by ikreymer** [comment]
Yeah, i was thinking about that too.. Probably just do a 302 on the server side, right, or can also do history.replaceState(), but that's less certain..

**Comment by tilgovi** [comment]
I was thinking 307 or 308, which both explicitly preserve the method.

**Comment by ikreymer** [comment]
Thinking about this further, I think that the url of the page should not be coupled to the baseURI.
Instead, I think it should be setting `document.baseURI` explicitly (if there is no `<base>` tag).

This would allow for other url encoding schemes to be used, if needed.

Thus for example, http://via.hypothes.is/example.com or http://via.hypothes.is/(com,example/) or http://example.via.hypothes.is/ should all have a `document.baseURI` of `http://example.com/`
which should be adequate to resolve urls.

I think currently the baseURI is lacking the trailing slash, I will see if I can fix this with the baseURI.

**Comment by tilgovi** [comment]
You might have to do that by inserting a base tag. The browsers that implement `document.baseURI` likely don't allow you to write it.

**Comment by ikreymer** [comment]
Chrome and FF do :)

If you visit `https://via.hypothes.is/example.com` in chrome or ff now, `document.baseURI` will `http://example.com`. 

For `https://via.hypothes.is/example.com/`, it'll be `http://example.com/`

So, need to add the slash in the first case.

For other browsers, yes, may need to rely on base...

**Comment by tilgovi** [comment]
Huh. I'm surprised. Lot's of document properties aren't writable like that. Or maybe I'm thinking of window.

**Comment by ikreymer** [comment]
Fixed in 0.10.9: http://pywb-h.herokuapp.com/https://ui.adsabs.harvard.edu
