### ISSUE TITLE
Change the LMS dev env to use py-proxy by default

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#35]
Change the LMS app's development environment to use the localhost py-proxy (localhost:9082 I think) rather than legacy Via, by default. (Devs will still need to have legacy Via running locally since py-proxy currently still forwards to legacy Via for HTML files.)

----

Things to do:

 * [x] Change LMS app env values to use our app (not NGINX) - https://github.com/hypothesis/lms/pull/1412
 * [x] Add to superdev - https://github.com/hypothesis/superdev/pull/11

**Comment by jon-betts** [comment]
PRs for this are in now
