### ISSUE TITLE
IE 11 & Edge trouble

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/via#36]
If I paste in the `embed.js` insertion code (see below) into the IE11 or Microsoft Edge, things work as expected.

However, if I go there via Via, then you get this error:
![screen_shot_2015-08-25_at_2 16 35_pm](https://cloud.githubusercontent.com/assets/43209/9583232/1c0feada-4fd8-11e5-968a-45a48382557f.png)

Not sure where to look for where to put a fix, but this does *seem* specifically Via related.

`embed.js` insertion code used when testing (via F12 Dev Tools):
```javascript
(function () {
// Only run injection for top-level window!
if (window != window.top) {
    return;
}

var embed_script = document.createElement("script");
embed_script.src = "https://hypothes.is/embed.js";
document.head.appendChild(embed_script);
window.hypothesisConfig = function() {
    return {showHighlights: true};
}
})();
```

**Comment by ikreymer** [comment]
Yes, seems like it doesn't like some of the rewriting.. Can try the latest, but probably not help.
Unfortunately, I do not have access to Edge currently.
