### ISSUE TITLE
via doesn't show annotations on Rolling Stone story

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#37]
For me, today, no annotations anchor for this link on Chrome, though via proxies the page and the sidebar is visible.  On Firefox it seems to be working fine. For others on Chrome it seems to be working fine.

https://via.hypothes.is/http://www.rollingstone.com/politics/news/the-point-of-no-return-climate-change-nightmares-are-already-here-20150805

Here is a screen shot of the page loading that shows the console.
https://goo.gl/NhYBMz

**Comment by ikreymer** [comment]
Hopefully the rewriting improvements in the latest pywb fix this?

**Comment by dwhly** [comment]
This is working for me now, closing.
