### ISSUE TITLE
Don't request resources from third-party servers

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#38]
The `/` (index) page [imports a CSS file from `unpkg.com`](https://github.com/hypothesis/py-proxy/blob/cb86165a5df897cc69e153eb1036190e8262a79a/py_proxy/templates/index.html.jinja2#L8). This can make page loading slow if the third-party server is slow to respond, and also means the page might break if the third-party edits or removes the file.

This issue is to remove the unpkg.com CSS file (move it into our own static assets) **and also find any other third-party resources** being used by any of py-proxy's endpoints and remove them.

Done when:

- [ ] The `normalize.css` file comes from our own static assets and is no longer downloaded from unpkg.com
- [ ] The py-proxy source code has been searched for any other third-party resources used by any endpoint, and any that are found have been removed or moved into our own static assets. Loading each endpoint in a browser and looking at the network requests may also help to find them

**Comment by jon-betts** [comment]
This may have been solved in the above linked PR (https://github.com/hypothesis/via3/pull/54)

**Comment by seanh** [comment]
I think this is done
