### ISSUE TITLE
Open sidebar by default

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#39]
Currently if you go to https://via3.hypothes.is/ and paste in a PDF URL it proxies the PDF and injects the client but doesn't open the client's sidebar. The user has to click to open the sidebar. While this matches legacy Via's behaviour it's probably not the best choice:

* Since the purpose of proxying something through Via is to annotate it (or to view annotations) not opening the sidebar automatically seems to be just making the user do an extra click
* Both bouncer and the LMS app do trigger the sidebar to open automatically, which I think suggests that that's the experience we want
* Users might not notice the client. The presence of the sidebar is sometimes the only difference between the proxied and non-proxied versions of the page (sometimes there are also highlights in the page, if the page already has annotations, but it's not necessarily obvious that you can click on these, they aren't buttons). The sidebar is pretty small and could easily be missed, hiding over at the right side of the window. Users might not understand.
* Mobile might be the one place where opening the sidebar automatically isn't desirable, since it takes up the entire screen and covers the entire document. The sidebar does currently open automatically on mobile in LMS and bouncer, though. And most usage is probably on desktop. So we should get the defaults right for desktop first.
* This card is limited to PDFs for now. The situation with HTML is slightly trickier since py-proxy, for now, forwards to legacy Via for HTML and legacy Via doesn't open the sidebar by default. py-proxy would have to add `via.open_sidebar=1` to the legacy Via URL that it redirects to.

**Comment by robertknight** [comment]
The sidebar is now opening automatically when visiting a PDF or HTML document with Via 3.

**Comment by tomcritchlow** [comment]
Is there any option or URL query string I can use to prevent the sidebar from opening on via.hypothes.is?
