### ISSUE TITLE
Support URLs without the leading http:// or https://

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#40]
If you go to https://via3.hypothes.is/ and type in "example.com" or "pdf995.com/samples/pdf.pdf" (with no leading http:// or https://) it'll crash. While invalid URLs do need to be handled with an error message (without crashing) (see <https://github.com/hypothesis/py-proxy/issues/23>, <https://github.com/hypothesis/py-proxy/issues/24>, and <https://github.com/hypothesis/py-proxy/issues/25>), URLs that are valid but just missing the leading http:// or https:// should be able to be handled correctly.

Legacy Via can handle these:

* <https://via.hypothes.is/example.com>
* <https://via.hypothes.is/pdf995.com/samples/pdf.pdf>

I don't know what legacy Via does to handle these (testing it or looking in its source code should tell you) but it probably prepends either http:// or https:// if the given URL doesn't already start with either. https:// is probably the better default.

We probably _should not_ prepend "www.".

**Comment by jon-betts** [comment]
Not that this matters too gravely, but this is expected behaviour right now rather than a bug. It's not good behavior, so we'd definitely expect better if we were sending users to this page.

**Comment by robertknight** [comment]
This is now mostly fixed:

- https://via.hypothes.is/example.com loads https://example.com in an iframe. The URL still shows https://via.hypothes.is/example.com however. Fixing https://github.com/hypothesis/viahtml/issues/156 would resolve this.
- https://via.hypothes.is/w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf loads https://w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf in the PDF viewer

**Comment by robertknight** [comment]
This is now done. The protocol can now be omitted both when submitting a URL on the index page and when visiting `https://via.hypothes.is/<URL>` directly.
