### ISSUE TITLE
Enable Brotli compression to speed up asset delivery

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#42]
[Brotli compression](https://en.wikipedia.org/wiki/Brotli) is a compression method for text based web content which can achieve higher compression ratios than gzip. There are two ways we can do this. We can turn it on everywhere in Cloudflare:

* https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-

This might backfire as [Brotli compression is good, but not fast](https://blog.cloudflare.com/results-experimenting-brotli/). What we might be better off doing is to use [`Whitenoise`'s support for compressing files](http://whitenoise.evans.io/en/stable/base.html#compression-support) at compile time. This also performs ahead of time gzip.

The advantage of this is:

 * The compression is done once, ahead of time, so we get the best of both worlds
 * It's applied only to static content (the Cloudflare setting might apply to everything)
 * Any customers who want to run the proxy, but not Cloudflare can benefit from it too
 
The disadvantage:

 * We have to introduce a step to build the files
 * If we can choose when to apply Brotli in Cloudflare, it's just a flick of a switch

----

Some numbers from testing locally with [`Whitenoise`'s support for compressing files](http://whitenoise.evans.io/en/stable/base.html#compression-support)

* Cloudflare GZIP: 303K
* Whitenoise GZIP: 302K (99.7%)
* ~Whitenoise Brotli: 229K (75.6%) - _24% is pretty good!_~ - Cloudflare ignores this hard
* Cloudflare Brotli: 279K (92.1%)

**Comment by seanh** [comment]
WhiteNoise comes with a CLI for doing the build-time compression: http://whitenoise.evans.io/en/stable/base.html#compression-support

If you're using Django WhiteNoise can compress the files for you automatically, you don't need to do the compression yourself in your build scripts: http://whitenoise.evans.io/en/stable/django.html#add-compression-and-caching-support I don't know how that works, but I wonder if we could implement the same as a Pyramid extension?

**Comment by jon-betts** [comment]
So this was done in https://github.com/hypothesis/via3/pull/58, but it turns out Cloudflare just ignores Brolti and only asks for gzip, so... great. I've added another PR to remove Brotli as it takes ages and has no benefit:

 * https://github.com/hypothesis/via3/pull/71

We can still enable it, although at a `*.hypothes.is` level in Cloudflare. This might be a good idea.

**Comment by jon-betts** [comment]
This has been all round the houses, but the final state is:

 * We enabled gzip compression on our end, but it only matters between us and Cloudflare
 * We enabled Brotli compression in general at the Cloudflare level
 * As it's on the fly, it's not as aggressive as our ahead of time Brotli, and so doesn't get the same benefits (10% rather than say 24% in some cases)
 * We abandoned our own Brotli because Cloudflare totally ignores it and it's slow
