### ISSUE TITLE
schoo blocking

### ISSUE THREAD

**Issue by easella** [hypothesis/via#497]
its blocked by my school

**Comment by jon-betts** [comment]
Hi, if the administrators at your school have blocked Via, then I'm afraid there's nothing much we can do about it.

You could ask your administrators to unblock it, or to add the [Hypothesis browser extension to Chrome](https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek) on your school network, or install the plugin yourself if you are allowed to use your own device. Installing our plugin allows you to annotate without access to Via:

* https://web.hypothes.is/start/ - Some instructions here

I'd be interested to know how you heard about our service? It's always good to hear how people found out about us!

**Comment by easella** [comment]
are there any more urls?
My school blocks all chrome extensions?

**Comment by jon-betts** [comment]
Sorry, if your school has blocked access to our service then we wouldn't want to go against their wishes. We often work with schools. In fact we're hoping to start working with more schools soon.

Perhaps you could pass on this invite to your teachers which could show them the benefits of using our software in your school:

> Intro to Social Annotation in Secondary Education
> 20 May @ 3:15pm–4:00pm PDT
> https://web.hypothes.is/event/intro-to-social-annotation-in-secondary-education-8/

Good luck!

**Comment by easella** [comment]
gggrrrrrrr.
please make a new link!
My teachers would never have a use for the annotation thing
