### ISSUE TITLE
via3.hypothes.is down

### ISSUE THREAD

**Issue by easella** [hypothesis/via#498]
![image](https://user-images.githubusercontent.com/74786054/118687812-70992800-b7d3-11eb-8c78-87b05e572a11.png)

**Comment by robertknight** [comment]
Hello. How did you get to this link? This looks like a temporary URL for a PDF file stored in Canvas. This would only have been accessible when launching a PDF assignment from our LMS app.

**Comment by jon-betts** [comment]
Quite a few regular client annotations on this here: https://hypothes.is/search?q=1e603ba9

**Comment by robertknight** [comment]
The via3.hypothes.is domain no longer exists. We've since replaced the public via.hypothes.is instance.
