### ISSUE TITLE
my school blocked via.hypothes.is? can you make a link like viaproxy.hypothes.is?

### ISSUE THREAD

**Issue by easella** [hypothesis/via#506]
![image](https://user-images.githubusercontent.com/74786054/119202386-a867d000-ba5e-11eb-8568-304d9927d6e6.png)

**Comment by robertknight** [comment]
Hello - you may be able to use the bookmarklet or Chrome extension if you are unable to access Via. If however you are trying to use via.hypothes.is to access a site that your school as blocked then that's not something that we can help with.
