### ISSUE TITLE
Call Checkmate before sending `GET` requests to third-party servers

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#543]
Slack thread: https://hypothes-is.slack.com/archives/C074BUPEG/p1627378641012800?thread_ts=1627359091.009000&cid=C074BUPEG

### Problem

When a public Via URL like <https://via.hypothes.is/https://example.com> is visited Via [sends a `GET` request to example.com to determine whether the URL is HTML or PDF](https://github.com/hypothesis/via/blob/d967aef42a38f3b8fa68c2e2b77e2821f84e4634/via/views/proxy.py#L13) and it looks like it _doesn't_ check whether the URL is blocked by Checkmate before sending this request.

As a result blocked websites that are slow to respond to this `GET` can cause performance issues for Via.

### Solution

Via should call Checkmate before doing this `GET` request.

This may result in multiple Checkmate checks for a single URL if Checkmate gets checked again by Via's PDF viewer or by Via HTML. This is probably fine: Checkmate requests are fast. We probably don't need to optimize it.

If it turns out that we _do_ need to optimize this we can probably do so based on the `Referer` header (Via and Via HTML could know that Checkmate has already been checked if the `Refer` points to Via). See the Slack thread (linked above) for more details. But don't implement this optimisation unless necessary.

## PR

 * https://github.com/hypothesis/via/pull/552

**Comment by jon-betts** [comment]
I _think_ this is working now, although it's a bit hard to tell. I'm seeing wacky behavior with the web archive save URL we had, but it's not hanging any more.

It just redirects back to the index page?

Other pages appear to be blocked as we'd expect.
