### ISSUE TITLE
via fails in edge

### ISSUE THREAD

**Issue by judell** [hypothesis/via#55]
SCRIPT5007: Unable to get property 'call' of undefined or null reference

wombat.js (763, 13)

**Update** - pywb issue discussed at https://github.com/ikreymer/pywb/issues/148

**Comment by judell** [comment]
Update: still failing but now the error is:

Can't redefine prop WB_wombat_top
wombat.js (379,13)

Not sure if that's because of an Edge update, pretty clearly the same thing under the covers.

**Comment by robertknight** [comment]
> wombat.js (763, 13)

Which is:

```js
        var get_baseURI = function() {
>           var res = orig_getter.call(this);
            return extract_orig(res);
        }
```
This is the same error that causes Via to fail in Safari - see https://github.com/hypothesis/via/issues/59

**Comment by robertknight** [comment]
The actual issue in Edge is slightly different than Safari - see https://github.com/ikreymer/pywb/issues/148 for specifics.
