### ISSUE TITLE
How to deploy a production instance?

### ISSUE THREAD

**Issue by fishfree** [hypothesis/via#554]
I have exactly the same problem as[ this one](https://github.com/hypothesis/lms/issues/3057).

**Comment by seanh** [comment]
Hi @fishfree, our dev mailing list would be a better place to ask for support: https://web.hypothes.is/developers/

It's not well documented but there is a `make docker` command that will build a Docker image that you can deploy. There are various environment variables you'd have to set, I'm afraid they're not well documented
