### ISSUE TITLE
Rename to Via 3

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#56]
Rename this project to Via 3 (or via3) everywhere:

- [x] Rename Python package from py_proxy to via3 (and replace any mentions of py_proxy or py-proxy found in the git repo contents) @jon-betts will do this part
- [x] Rename the GitHub repo to github.com/hypothesis/via3
- [x] Deploy to via3.hypothes.is and qa-via3.hypothes.is (already done)
- [x] It should be named via3 in the deployment repo
- [x] It should be named Via 3 on Jenkins
- [x] It should be named Via 3 in Elastic Beanstalk
- [x] Sentry
- [x] New Relic <- We seem to have "via3", "via3 (qa)" and "via3 (prod)" in New Relic. One of them shouldn't be there
- [ ] Other monitoring and infra stuff?

**Comment by jon-betts** [comment]
Renamed things in the repo in: https://github.com/hypothesis/via3/pull/75
