### ISSUE TITLE
Use resource keys when proxying Google Drive files

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#567]
For Google Drive files that have a resource key Via should pass that resource key to Google when proxying the file.

This needs to include:

- [ ] LMS assignments where [we saved a resource key when creating the assignment](https://github.com/hypothesis/lms/pull/3070) (more generally: any `drive.google.com` URL with a `resourceKey` param on it)
- [ ] Pre-existing Google Drive URLs that we [got resource keys for](https://github.com/hypothesis/private-issues/issues/70)

We'll need to figure out how you actually use a resource key when downloading a file from Google Drive.

This may depend on <https://github.com/hypothesis/via/issues/570>: if we're going to be moving proxying off Google Drive PDFs from NGINX to Python then we can implement resource key support in the new Python version rather than in NGINX.

## PRs

* https://github.com/hypothesis/devdata/pull/31
* https://github.com/hypothesis/via/pull/582

**Comment by jon-betts** [comment]
Some hints about setting a header for this here:

 * https://developers.google.com/drive/api/v3/resource-keys
