### ISSUE TITLE
Fix Via's drive.google.com URL rewriting to also work with URLs that have resource keys

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#568]
Via's NGINX config dynamically [rewrites `drive.google.com` URLs into `googleapis.com` URLs](https://github.com/hypothesis/via/blob/b4839541d21ba63a05fccf8f6334ec7dd58da5ce/conf/nginx/includes/proxy.conf#L51). This is important because the `googleapis.com` URLs are authenticated using our Google Drive API key and have different rate limits.

[New Google Drive assignments created by the LMS app can have `resourcekey` params in them](https://github.com/hypothesis/lms/pull/3070) NGINX's regex-based rewriting fails to match those.

This may depend on <https://github.com/hypothesis/via/issues/570>: if we're going to be moving proxying off Google Drive PDFs from NGINX to Python then we won't need to fix the URL rewriting in NGINX since it's being replaced.

PRs:

 * https://github.com/hypothesis/via/pull/582

**Comment by jon-betts** [comment]
It might not be possible to do this in NGINX in a sane way. We may need to construct the header:

* https://developers.google.com/drive/api/v3/resource-keys

And pass it to our request to NGINX. We can presumably get NGINX to pass it along easily enough.

**Comment by seanh** [comment]
It looks like we're probably going to change to using Python rather than NGINX to proxy files from Google Drive (see: https://github.com/hypothesis/via/issues/570) in which case we'll just be deleting this rewrite from the NGINX code (and making sure not to make the same mistake in the Python code). If so we can close this issue when we delete the code from NGINX

**Comment by seanh** [comment]
We're not gonna do this as we've moved the proxying into Python. I made a separate issue to delete the Google Drive special handling from NGINX: https://github.com/hypothesis/via/issues/595
