### ISSUE TITLE
Fix Via's PDF detection optimization for drive.google.com URLs to also work with URLs that have resource keys

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#569]
Via's PDF-versus-HTML detection contains [an optimization for `drive.google.com` URLs](https://github.com/hypothesis/via/blob/f6383f688034d3af536407d5bba45983f4604a26/via/get_url/details.py#L59-L60) that skips a network request to Google by assuming that the document is a PDF. This is important because it avoids an unnecessary network request and also avoids unauthenticated traffic to Google Drive that would get rate limited.

Some new Google Drive assignments created in the LMS app [have `resourcekey` params on them](https://github.com/hypothesis/lms/pull/3070) and the regex used by the above optimization will fail to match them.

# PRs

 * https://github.com/hypothesis/via/pull/582

**Comment by jon-betts** [comment]
This is done now
