### ISSUE TITLE
Use OAuth service account authentication to proxy Google Drive PDFs

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#570]
Instead of an API key use a service account (with OAuth authentication) when proxying PDFs from Google Drive. This is to avoid [403 Forbidden: your computer or network may be sending automated queries](https://docs.google.com/document/d/1QDCnUaWRHIkZhCyfvscz5oKknXCyVxx-GlGqErg41YU/edit#heading=h.9vmm5rqkzf6t) errors from Google Drive: we believe that service account authentications gets a much higher rate limit than API authentication.

Note that any new solution for proxying Google Drive PDF's is going to need to have [support for resource keys](https://github.com/hypothesis/via/issues/567).

**PRs**

* https://github.com/hypothesis/via/pull/565
* https://github.com/hypothesis/devdata/pull/29
* https://github.com/hypothesis/devdata/pull/30
* https://github.com/hypothesis/via/pull/572
* https://github.com/hypothesis/via/pull/564
* https://github.com/hypothesis/via/pull/579
* https://github.com/hypothesis/devdata/pull/31
* https://github.com/hypothesis/via/pull/580

Discovered during testing:

 * https://github.com/hypothesis/via/pull/581

Suggestions for follow-up PRs:

* Enable Cloudflare caching (either by removing via.sec or other means)
*  Include the response body (excerpted) (when there is one) in the Error Details
*  Send exceptions to Sentry. Both when there is a sensible response body (e.g. a 403 from Google) (and make sure the response body appears nicely in Sentry) and when there isn't (e.g. random socket error in the middle of streaming the file) 
* (Use a separate exception view for Google files stuff, ensure we stringify nicely for Sentry)
 Special-case 404's because Google files have been deleted. These can have a 404 status code and can not get reported to Sentry

**Comment by jon-betts** [comment]
From @seanh :

> These old notes of mine have some details about when Sentry's Pyramid integration does and doesn't report exceptions: https://www.seanh.cc/2019/09/19/pyramid-retry/ Including that Pyramid HTTPError subclasses don't get reported and that exceptions handled by exception views don't get reported. I think if your exception view returns a 500 status it does still get reported otherwise not. But anyway you just want to call h-pyramid-sentry's report_exception() manually (https://github.com/hypothesis/h-pyramid-sentry/blob/fa3a0b560d0a077ec375dea94cc8900f4d47a96b/src/h_pyramid_sentry/__init__.py#L14-L23)

**Comment by jon-betts** [comment]
This just needs to be enabled in live at the moment

**Comment by seanh** [comment]
This is done. Separate issues have been created for all the followup tasks
