### ISSUE TITLE
Figure out how to get backported Google Drive resource keys into Via

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#571]
Once we've [gotten resource keys for all existing Google Drive URLs in our databases](https://github.com/hypothesis/private-issues/issues/70) we need a way to get those resource keys into Via so that we can [use them when proxying PDF files](https://github.com/hypothesis/via/issues/567).

The resource keys will likely be a JSON file larger than 4KB.

**Comment by indigobravo** [comment]
I think we have a solution...


### Overview
The following has been put together.

1. There is an S3 bucket [(via-data)](https://s3.console.aws.amazon.com/s3/buckets/via-data?region=us-west-1&tab=objects) that can be used to store configs and such.
    - _The bucket is private, and has versioning and encryption enabled._
 2. A platform customisation has been created to download files from the S3 bucket and save them to a directory on the EC2 server running the lms-via Docker container.
 3. Our Docker config has been updated to mount the directory from the EC2 server to the container.


### How can the data be accessed
Specific files from the [via-data](https://s3.console.aws.amazon.com/s3/buckets/via-data?region=us-west-1&tab=objects) S3 bucket are made available in the `/via-data` directory on both the EC2 server and Docker container.


### How to update the data made available to the docker container
1. Copy file to the [via-data](https://s3.console.aws.amazon.com/s3/buckets/via-data?region=us-west-1&tab=objects) S3 bucket. 
2. Update the [10_via-data.sh](https://github.com/hypothesis/deployment/blob/master/lms-via/platform/prod/hooks/prebuild/10_via-data.sh) platform hook.


### Next steps
The update been deployed to both Prod and QA environments, and the `/via-data` mount points presents a file I have been using for testing. Once the real Google Drive resource key data available, let me know and I will perform the required updates.

**Comment by seanh** [comment]
This is done now
