### ISSUE TITLE
Include Google Drive response bodies in our own response bodies

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#584]
When [proxying Google Drive files in Python](https://github.com/hypothesis/via/blob/91847a432a58ea5e054b79ce27182f211ee42e72/via/views/google_drive.py#L9-L29) if we get an error response from Google Drive we should include the response body from Google Drive in the response that we send back to the browser, for debugging purposes.

The response that we send back to the browser **should not be a custom HTML page** (as it is currently): these error responses don't get rendered in browsers. You have to go into dev tools to see them. And dev tools will show you the raw HTML not rendered. A complex HTML page is unreadable in this context.

Options:

1. A simple JSON response including the original response body from Google Drive stringified into the JSON

2. Just use the original response body from Google Drive directly as our own response body. Why bother wrapping it in some JSON of our own? Seems pointless.

   One reason why we might stringify Google's body into our own JSON is if we also want to include something else in the JSON. For example including the HTTP _status_ from Google in the JSON as well as the body from Google. It will not be necessary to include the status in the body if we decide to proxy the status directly (https://github.com/hypothesis/via/issues/596), but if we don't proxy statuses directly then we must include them in the body instead.

**Comment by seanh** [comment]
Note that we've also decided to change these HTML error pages to JSON for the Google Drive endpoint, so the task will be to include the body in the JSON. See https://github.com/hypothesis/via/issues/590

**Comment by robertknight** [comment]
I don't have a particularly strong opinion here, other than that it should be easy for a developer or technical user (eg. support) to get the original response body in some form. 

> Just use the original response body from Google Drive directly as our own response body. Why bother wrapping it in some JSON of our own? Seems pointless.

An upside of wrapping the response is that it is obvious that where the original response comes from. A downside is that it is a bit harder to read if it is HTML stuffed inside JSON.

An example error response from Google Drive for an invalid file ID looks like this:

```html
<HTML>
<HEAD>
<TITLE>Not Found</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Not Found</H1>
<H2>Error 404</H2>
</BODY>
</HTML>
```

The upper-case HTML tags and obsolete attributes clues me in to the fact that this comes from Google, but it might not be obvious to other people.

**Comment by seanh** [comment]
I think this is blocked by <https://github.com/hypothesis/via/issues/596> and the outcome of [this discussion](https://hypothes-is.slack.com/archives/CR3E3S7K8/p1631184261040800?thread_ts=1631115030.022700&cid=CR3E3S7K8). We need to decide whether we're going to return a JSON body with Google's original response serialized into the JSON, or just return Google's original response directly.

**Comment by jon-betts** [comment]
The error from Google Drive for an invalid ID is JSON when using the API.

**Comment by jon-betts** [comment]
Done!
