### ISSUE TITLE
Via causes JS errors on many pages in Safari 9

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#59]
Via fails with many pages in Safari 9 (and possibly earlier versions, I haven't tested), due to errors when replacing the getters/setters for `document.cookie` and other properties.

Steps to reproduce:
1. Run Via locally and access a trivial HTML page (just the HTML `<a href="index.html">Click me</a>` works)
2. Open Safari 9 and inspect "document.cookie" in the dev tools

Expected:
- Return value is a string

Actual:
- Return value is `undefined`. Needless to say, this breaks JS on many pages which try to do string operations on `document.cookie`.

The cause of the issue is that `wombat.js` tries to replace `document.cookie`'s setter but keep the original getter using `def_prop($wbwindow.document, "cookie", set_cookie, orig_get_cookie);` where `orig_get_cookie` is undefined. `orig_get_cookie` is looked up using `document.__lookupGetter__('cookie')` which returns a native function in Chrome and Firefox but undefined in Safari.

**Comment by robertknight** [comment]
`wombat.js` uses two methods to lookup the original getters and setters for DOM functions, the deprecated `__lookupGetter__` method and `Object.getOwnPropertyDescriptor()`.

On Safari 9, `document.__lookupGetter__('cookie')` returns undefined as noted in the previous comment and the result of `Object.getOwnPropertyDescriptor(Document.prototype, 'cookie')` is:

```js
{
  get: undefined,
  set: undefined, 
  enumerable: true,
  configurable: false,
}
```

See also: https://bugs.webkit.org/show_bug.cgi?id=140575

**Comment by robertknight** [comment]
Via is completely broken in Safari 8 and 9 due to a similar issue when trying to override `document.baseURI` with with `pywb` >= 0.10.2. With py 0.10.1, Via works with Safari, with later versions it fails due to this error.

**Comment by robertknight** [comment]
The change in H to use `document.baseURI` rather than a different method happened with 0dee222385abcbc2138803ca120427ef0a8409f9

**Comment by judell** [comment]
Perhaps related: #55

**Comment by robertknight** [comment]
Related pyweb issue: https://github.com/ikreymer/pywb/issues/147

**Comment by robertknight** [comment]
Whilst investigating this I made some notes on exactly what the live rewriting in pywb currently does: https://gist.github.com/robertknight/2145c99ed8209ebb1b81
