### ISSUE TITLE
Consider proxying HTTP status codes from Google Drive

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#596]
We should re-consider directly proxying all HTTP error response statuses from Google Drive, without messing with them.

Reasons why I think we should consider doing this:

* The status code can be seen by users (or Hypothesis support staff or developers looking at screenshots from users) and it can carry meaningful information. E.g. 404 or 403.

* The status code can be useful in monitoring and alerting. For example [we want to set a particularly sensitive alarm or notification for 403s](https://github.com/hypothesis/playbook/issues/735) from Google Drive in case we're getting rate limited again.

Putting the status code in the _body_ of our response achieves neither aim. It's much harder for users to see (they need to open dev tools, find the right request, and click on the _Response_ tab) and it can't be used by monitoring and alerting tools.

**Comment by robertknight** [comment]
I agree. Proxying the upstream status codes in this case is probably going to be a pragmatic behavior that is useful for diagnosing problems and monitoring. There are some risks with doing so, as it makes it harder for example to find all the places in the app that might report a particular status code, and an unexpected upstream status code could potentially trigger alerts set up for some other purpose. However we could always revisit this if that problem did actually materialize.

**Comment by seanh** [comment]
Slack thread: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1631115030022700

**Comment by seanh** [comment]
We've ended up with code that parses Google's error responses and translates them into different Via error responses based on the status code and body from Google. For example when Google gives us a 403 because we don't have permission to download the file (e.g. the file isn't shared) we send a 403 back to PDF.js; when Google gives us a 403 because it's rate limiting us we turn that into a 429 that we send back to PDF.js; etc. See https://github.com/hypothesis/via/pull/617, https://github.com/hypothesis/via/pull/618, https://github.com/hypothesis/via/pull/619, https://github.com/hypothesis/via/pull/624 and https://github.com/hypothesis/via/pull/626. The most relevant part of the code seems to be the `translate_google_error()` function:

https://github.com/hypothesis/via/blob/4b04379fc889285001f7c4bc3580af61c5180525/via/services/google_drive.py#L19-L59

I did some testing of this solution...

## Current behaviour

### Google Drive file doesn't exist

To test this you can hack Via's code to always use a non-existent file ID for Google Drive assignments:

```diff
diff --git a/via/services/google_drive.py b/via/services/google_drive.py
index 0849ae2..62a65aa 100644
--- a/via/services/google_drive.py
+++ b/via/services/google_drive.py
@@ -146,7 +146,7 @@ class GoogleDriveAPI:
         :raises UpstreamServiceError: For other errors
         """
         # https://developers.google.com/drive/api/v3/reference/files/get
-        url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
+        url = f"https://www.googleapis.com/drive/v3/files/xyz123?alt=media"
 
         headers = add_request_headers(
             {
```

Then launch a Google Drive assignment. Result:

1. The user will see a **Missing PDF file** error message from PDF.js
2. If they look in the developer tools that user will see a 404 response from Via with this JSON body: `{"exception": "HTTPNotFound", "message": "File id not found"}`
3. The original status code from Google is not accessible (although it happens to be the same as the Via status code that we use in this case)
4. The original error response body from Google is not accessible
5. Nothing gets reported to Sentry (which is probably what we want)

### We are being rate-limited by Google Drive

To reproduce this hack Via's code to call [Via Test App's fake Google Drive rate-limit-exceeded error page](https://github.com/hypothesis/via_test_app/pull/7/files) instead of calling the real Google Drive:

```diff
diff --git a/via/services/google_drive.py b/via/services/google_drive.py
index 0849ae2..bf1c2a9 100644
--- a/via/services/google_drive.py
+++ b/via/services/google_drive.py
@@ -146,7 +146,7 @@ class GoogleDriveAPI:
         :raises UpstreamServiceError: For other errors
         """
         # https://developers.google.com/drive/api/v3/reference/files/get
-        url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
+        url = f"http://localhost:9101/google-drive/rate-limit-exceeded"
 
         headers = add_request_headers(
             {
```

Then launch a Google Drive assignment. Result:

1. The user sees an **Unexpected server response** error message in PDF.js

2. If they look in the developer tools that user will see a 429 Too Many Requests response from Via with this JSON body: `{"exception": "GoogleDriveServiceError", "message": "Too many concurrent requests to the Google Drive API", "upstream": {"status_code": 403, "content_type": "application/json", "url": "http://localhost:9101/google-drive/rate-limit-exceeded", "json": {"error": {"errors": [{"reason": "userRateLimitExceeded"}]}}}}`

   The use of 429 Too Many Requests here is a little odd because it implies that PDF.js / the user's browser has been sending too many requests to Via which is not the case. This could potentially be misinterpreted by Via, Cloudflare, AWS, NGINX, or something else along the way. Hopefully it has no effect in practice.

3. The original status code from Google is available in the JSON body of Via's response (see above)

4. The original error response body from Google is available in the JSON body of Via's response (see above)

5. A `GoogleDriveServiceError` exception does get reported to Sentry, but you can't see Google's original error response body in Sentry

### We don't have permission to download the file from the Google Drive API

I think it should be possible to create a test file set up in this way in Hypothesis's Google Drive account. But for now, to reproduce this issue, hack Via's code to call Via Test App's fake Google Drive cannot-download-file error page instead of calling the real Google Drive:

```diff
diff --git a/via/services/google_drive.py b/via/services/google_drive.py
index 0849ae2..49f42fa 100644
--- a/via/services/google_drive.py
+++ b/via/services/google_drive.py
@@ -146,7 +146,7 @@ class GoogleDriveAPI:
         :raises UpstreamServiceError: For other errors
         """
         # https://developers.google.com/drive/api/v3/reference/files/get
-        url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
+        url = f"http://localhost:9101/google-drive/cannot-download-file"
 
         headers = add_request_headers(
             {
```

Then launch a Google Drive assignment. Result:

1. The user sees an **Unexpected server response** error in PDF.js

2. If they look in the developer tools the user will see a **403 Forbidden** error response from Via with this JSON body: `{"exception": "GoogleDriveServiceError", "message": "We do not have permission to download the file through the Google Drive API", "upstream": {"status_code": 403, "content_type": "application/json", "url": "http://localhost:9101/google-drive/cannot-download-file", "json": {"error": {"errors": [{"reason": "cannotDownloadFile"}]}}}}`

3. The original status code from Google is available in the JSON body of Via's response (see above)

4. The original error response body from Google is available in the JSON body of Via's response (see above)

5. Nothing gets reported to Sentry (which is probably what we want)

### Unexpected error from Google

The three examples above are implemented by us parsing Google's error responses and special-casing certain types of error based on their status code and JSON body. If Google changes the status code and/or JSON body that it uses for any of the above cases they'll no longer be caught by our special-casing. Also if we encounter an error we haven't seen before it won't be caught.

To test this type of error hack Via's code to call Via Test App's fake Google Drive unexpected-error page instead of calling the real Google Drive:

```diff
diff --git a/via/services/google_drive.py b/via/services/google_drive.py
index 0849ae2..49f42fa 100644
--- a/via/services/google_drive.py
+++ b/via/services/google_drive.py
@@ -146,7 +146,7 @@ class GoogleDriveAPI:
         :raises UpstreamServiceError: For other errors
         """
         # https://developers.google.com/drive/api/v3/reference/files/get
-        url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
+        url = f"http://localhost:9101/google-drive/unexpected-error"
 
         headers = add_request_headers(
             {
```

Then launch a Google Drive assignment. Result:

1. The user sees an **Unexpected server response** error in PDF.js

2. If they look in the developer tools the user will see a **417 Expectation Failed** error response from Via with this JSON body: `{"exception": "UnhandledUpstreamException", "message": "403 Client Error: Forbidden for url: http://localhost:9101/google-drive/unexpected-error", "upstream": {"status_code": 403, "content_type": "application/json", "url": "http://localhost:9101/google-drive/unexpected-error", "json": {"error": {"errors": [{"reason": "unexpectedReason"}]}}}}`

3. The original status code from Google is available in the JSON body of Via's response (see above)

4. The original error response body from Google is available in the JSON body of Via's response (see above)

5. An `UnhandledUpstreamException` gets reported to Sentry, but you can't see Google's original error response in Sentry

### Unexpected JSON format from Google

It's possible for certain unexpected JSON formats to cause our Google Drive JSON parsing code to crash and trigger a 500 Internal Server Error from us. Fix for two of these issues: https://github.com/hypothesis/via/pull/640 Hopefully there are no more such crashes after that fix.

```diff
diff --git a/via/services/google_drive.py b/via/services/google_drive.py
index cfb02c1..0356617 100644
--- a/via/services/google_drive.py
+++ b/via/services/google_drive.py
@@ -155,7 +155,7 @@ class GoogleDriveAPI:
         :raises UpstreamServiceError: For other errors
         """
         # https://developers.google.com/drive/api/v3/reference/files/get
-        url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
+        url = f"http://localhost:9101/google-drive/unexpected-json-format"
 
         headers = add_request_headers(
             {
```

With those crashes fixed an unexpected JSON format is the same as above: **Unexpected server response**, 417, original status code and body in our JSON body, exception reported to Sentry but without the error body.

I haven't tested this but looking at the code I think a response error that claimed to be JSON but wasn't valid JSON at all would get handled in the same way.

### Non-JSON error from Google

What if Google sends us a non-JSON response, such as an HTML page (which we've seen before)?

```diff
diff --git a/via/services/google_drive.py b/via/services/google_drive.py
index cfb02c1..c84a5b7 100644
--- a/via/services/google_drive.py
+++ b/via/services/google_drive.py
@@ -155,7 +155,7 @@ class GoogleDriveAPI:
         :raises UpstreamServiceError: For other errors
         """
         # https://developers.google.com/drive/api/v3/reference/files/get
-        url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
+        url = f"http://localhost:9101/google-drive/html"
 
         headers = add_request_headers(
             {
```

Results are the same as for unexpected JSON.

## Potential issues with current behaviour

- [ ] When we get a 404 `notFound` from Google the original error status and body aren't included in Via's error response. This seems pretty minor given that it only happens for 404 `notFound` errors. Not going to create an issue for this.

- [ ] The bodies of error responses from Google aren't available to us in Sentry.

  This applies to all error responses from Google but it seems particularly important for _unexpected_ errors:

  If the error response from Google is one of those that we recognise and special-case (404 `notFound`, 403 `userRateLimitExceeded`, or 403 `cannotDownloadFile`) then each of these results in a unique status code from Via (albeit different from Google's original status) so we kind of know what the error body from Google must have been (at least we know it must have been something that matched our special case parsing).

  But if the error response from Google is not one of those that we special case then we just turn any other error response from Google into a 417 and we can't distinguish them from each other or see what the original error body was in our monitoring. We *do* include the original body in Via's response body but that's only good to us if users copy-paste the response from dev tools for us or if we can reproduce the problem. We really need the bodies in Sentry as well.

  Note that the original status code from Google actually is visible in Sentry just not the body.

  Opened a separate issue for this: https://github.com/hypothesis/via/issues/641
