### ISSUE TITLE
Via failing in Firefox

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#6]
Open Firefox.  Go here:
https://via.hypothes.is/h/http://nieman.harvard.edu/fellowships/

The app loads briefly and then disappears.

**Comment by dwhly** [comment]
I think it was our H. FF extension that is doing this.

**Comment by ikreymer** [comment]
ah ok.. although, in that situation, where user has extension and uses via, should one of them not do anything to avoid double-init? I recall there should be a check for that by checking `window.annotator` but let me know if anything needs to be added..
