### ISSUE TITLE
Enable immutable URLs for static files so they can be cached forever

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#60]
WhiteNoise supports setting the appropriate cache headers to [allow immutable files to be cached forever](http://whitenoise.evans.io/en/stable/base.html#caching-headers) but this requires us to have a build system that generates immutable filenames (such that if the contents of the static file change, its filename and therefore its URL also change):

> Most modern static asset build systems create uniquely named versions of each file. This results in files which are immutable (i.e., they can never change their contents) and can therefore by cached indefinitely. In order to take advantage of this, WhiteNoise needs to know which files are immutable. This can be done using the immutable_file_test option which accepts a reference to a function.

It would be good to enable this but we'd need to do the work of setting up a build system such that static files get a hash of their contents put into their filenames or something like that

For: https://github.com/hypothesis/via3/issues/31

**Comment by jon-betts** [comment]
Enabled in https://github.com/hypothesis/via3/pull/77

Also arguably part of https://github.com/hypothesis/via3/issues/32

**Comment by jon-betts** [comment]
This is deployed out now. The net effect is very good for the static files, but from my machine the base file is taking about 600ms to get. This is very slow for a plain HTML page.

I suspect SSL again, but I'm not sure. David said that we might have 2 different NGINX's in a chain on our side, which might have something to do with it.

On the plus side our content will currently change instantly which is nice.
