### ISSUE TITLE
Filter out exceptions from `route_by_content()` talking to third-parties

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#612]
When the `route_by_content()` view [sends requests to third-parties](https://github.com/hypothesis/via/blob/38f0c85e679f93b3d112a92437ca84aee74ff98e/via/views/route_by_content.py#L17) we don't want exceptions from those requests to get logged. They're just a lot of noise in our monitoring systems.

### Done when

- [ ] Exceptions from `route_by_content()` talking to third-parties don't get reported to Slack
- [ ] Exceptions from `route_by_content()` talking to third-parties don't get logged to Papertrail
- [ ] **All** exceptions from Via talking to Google Drive do still get logged to both Papertrail and Slack.

  `route_by_content()` [doesn't send requests to Google Drive](https://github.com/hypothesis/via/blob/38f0c85e679f93b3d112a92437ca84aee74ff98e/via/get_url.py#L27-L28) because it just assumes that drive.google.com URLs are PDFs.

  So we just need to make sure that all the requests [sent by `GoogleDriveAPI`](https://github.com/hypothesis/via/blob/38f0c85e679f93b3d112a92437ca84aee74ff98e/via/services/google_drive.py#L125-L128) are still getting reported.

### Implementation notes

We probably want to make it raise one exception class for `route_by_content()` errors and a different exception class for Google Drive proxying errors, as that's what's going to make filtering from both tools easiest.

`pyramid_exclog` is the thing that's logging these exceptions to Papertrail. It has an `exclog.ignore` setting for filtering out exceptions: <https://docs.pylonsproject.org/projects/pyramid_exclog/en/latest/#settings>.

`h-pyramid-sentry` is the thing that's logging these exceptions to Sentry. It has an `h_pyramid_sentry.filters` setting for filtering things out: <https://github.com/hypothesis/h-pyramid-sentry#filters>. Also see Sentry's [Filtering for Python](https://docs.sentry.io/platforms/python/configuration/filtering/) and [Inbound Filters](https://docs.sentry.io/product/data-management-settings/filtering/) docs for other ways.

**Comment by jon-betts** [comment]
This is quite easily done with a different exception handler. 

Exceptions raised by 3rd party things are all requests exceptions. These are mapped to our three exception types. So if we don't call `exc_log` on them, then we don't need to filter them back out again.

**Comment by seanh** [comment]
You mean if we don't call `report_exception()`?

**Comment by jon-betts** [comment]
Done in: https://github.com/hypothesis/via/pull/614
