### ISSUE TITLE
Keep an eye on Google Drive timeouts

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#616]
We've been seeing some timeouts from Google. We're hoping that recent work upping the timeouts on our side will help, but we should check back and see if it has.

We don't get many errors so it's not the sort of thing we can verify immediately.

We also have an oddity where `Timeout` objects raised by the Google code don't have any useful information in them. This could be fine though given the context. If we have a URL and we see a Timeout object we probably know what's going on?

## Bugs spotted / fixed

 * https://github.com/hypothesis/via/pull/630
 * https://github.com/hypothesis/via/pull/631
 * https://github.com/hypothesis/via/pull/632
 * https://github.com/hypothesis/via/pull/637
 * https://github.com/hypothesis/via/pull/636

**Comment by jon-betts** [comment]
I've spotted a few timeouts at 30s today. I'm not really sure what more is to be done here?

I could investigate if they are particularly large files:

* https://sentry.io/organizations/hypothesis/issues/2680754992/?project=1881822&query=is%3Aunresolved

**Comment by seanh** [comment]
We're not seeing many of these timeouts
