### ISSUE TITLE
Annotations created in Via with Edge do not appear when viewing the same page with Firefox/Chrome

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#64]
**Steps to reproduce**

1. Open https://via.hypothes.is/example.com in Edge and add an annotation
2. Open https://via.hypothes.is/example.com in Firefox, signed in as the same user

**Expected**

Annotation added in (1) is visible in (2)

**Actual**

Annotation added in (1) is only visible in Edge/IE, not Firefox/Chrome. When the client searches for annotations in IE/Edge, it performs a search against 'https://via.hypothes.is/$URL' instead of $URL and presumably the same when adding annotations.

**Comment by ikreymer** [comment]
This is due to the more limited rewriting ability on these browsers.. Perhaps the inject script could be configured to check for a certain prefix, and strip it out, eg. if a url starts with 'via.hypothes.is', it should remove that part? Could also do server-side but probably easier/better on the client.

**Comment by robertknight** [comment]
@ikreymer The problem in this case is somewhere on our end. The page has a `<link rel="canonical" href="$ORIGINAL_URL">` at the top, so Hypothesis should treat any annotations added as being associated with $ORIGINAL_URL.

**Comment by robertknight** [comment]
This is an issue related to Edge, the URL polyfill and possibly Via's rewriting:

When retrieving the metadata for the document, `guest.coffee` in H does this:

```(new URL(<canonical URL from link tag>, document.baseURI)).toString()`

In Firefox under Via this evaluates to `<canonical URL>`, in Edge with the URL polyfill it evaluates to `<via URL>/<canonical URL>`.

**Comment by robertknight** [comment]
The issue is happening here because of the interaction between a polyfill for
URL and Wombat's overrides for `HTMLAnchorElement`, which modifies the `href`
getter and setter but does not override `HTMLAnchorElement.toString`, which
is supposed to be a synonym for the href property.

1. Edge lacks a URL() ctor, so the URL polyfill from `js-polyfills` is used. This polyfill
    uses DOM elements (specifically HTMLAnchorElement) to do a bunch of the work.
    That DOM class has been monkey patched by Wombat - and this is where the problem lies.

2. When 'new URL(url, base)' is called, the URL polyfill creates a new document
   containing a `<base>` tag in the head set to `base` and an anchor tag
   whose href is set to `url` via `anchor.href = url`.
   
   WombatJS has overridden the `HTMLAnchorElement.href` setter so that it prepends
   the Via URL to the element. Hence the anchor's actual href is set to
   `$via_url/$url`
   
   Later on, the URL object is converted back into a string. Internally this
   uses HTMLAnchorElement.toString(), which returns the real href of the anchor,
   whereas accessing the HTMLAnchorElement.href property would have invoked Wombat's
   custom href getter implementation, which would have converted `$via_url/$url` back
   to `$url`
