### ISSUE TITLE
Send Google Drive error response bodies to Sentry

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#641]
Google Drive error response bodies currently aren't being sent to Sentry which will limit our ability to diagnose any Google Drive issues in production, see https://github.com/hypothesis/via/issues/596#issuecomment-933704588. We should make sure that all Google Drive error bodies do appear in Sentry reports.

IIRC the trick here is to make sure that the `__str__()` of the exception object includes the response body. For example this is how LMS does it: https://github.com/hypothesis/lms/blob/2e2113e425fd4b5f9d46fe655bf0aad917eb8545/lms/services/exceptions.py#L21-L34

It may be worth a re-read of the Sentry docs to see if there's a better way now.

There are quite a lot of things about how-to-use-`requests`-properly that are handled by LMS's `HTTPService`, including this. It might be worth extracting that service into a library and having Via use it. The exceptions code is currently being refactored / fixed in LMS though so it's not really in a nice-to-extract state right now. So for the time being probably just fix this in Via

**Comment by jon-betts** [comment]
Done
