### ISSUE TITLE
Project Gutenberg doesn't like Via

### ISSUE THREAD

**Issue by JonathanReeve** [hypothesis/via#7]
Try visiting, for instance: 
 * https://via.hypothes.is/http://www.gutenberg.org/files/4300/4300-h/4300-h.htm

It 403s with the error: 

    Error 403
    Maybe you have just a wrong url. Go to http://www.gutenberg.org/ebooks/ first to see if the error persists.

It seems Gutenberg checks its own URLs before serving pages.

**Comment by tilgovi** [comment]
If that's the case, as the message suggests, there is probably nothing we can do.

**Comment by ikreymer** [comment]
It appears that Project Gutenberg is blocking amazon IP addresses. I also get the same error for webrecorder.io unfortunately. I think the only option is to request them to exclude the host that via is running on from the ip block.

**Comment by lenazun** [comment]
I'll close this as won't fix. We've reached out to Project Gutenberg but still no success, not much we can do.
