### ISSUE TITLE
Spike to determine how much HTML rewriting Via 3 needs to do

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#7]
Depends on:

* [Create HTML testing spreadsheet](https://github.com/hypothesis/py-proxy/issues/20) (issue to create a spreadsheet of test URLs that we'll use)

Before we can plan how to implement an HTML rewriting proxy, we crucially need to know how much rewriting it needs to do and, in particular, how much of that rewriting needs to be done server-side rather than client-side.

The answers to these questions will have a big impact on how we decide to implement the rewriting proxy. For example, if a really large amount of complex server-side rewriting is needed then it may not be practical to do it all using regexes in Nginx. We may need to use a server-side HTML parsing library, even though that's going to be slower and less efficient. On the other hand, if only a small amount of simple server-side rewriting is needed we may be able to do that with just a handful of regexes, and introducing an HTML parsing library would be an unnecessary cost.

## See Also

* [Spike to determine how we'll implement HTML rewriting](https://github.com/hypothesis/py-proxy/issues/8). A follow-on spike, to be delivered after this one, to decide how we'll implement the proxy. Deciding how we'll implement the proxy is out of the scope of _this_ spike (https://github.com/hypothesis/py-proxy/issues/7), which is just about deciding _what_ we need to implement (gathering requirements).
*  [The spreadsheet](https://docs.google.com/spreadsheets/d/14rldiXZKlDC7ZzWOIvC5Ky8bgxJhBOIGgE6NWroaNJQ/) we'll use to answer this spike's questions

## Scope

* For now, Via 3's HTML rewriting is only intended to be used by the LMS app. We're not attempting to replace the public <https://via.hypothes.is/> in this first step.
* Clicking on links within the page doesn't need to "stay within" the proxy
* JavaScript ads don't need to continue to work
* Remember that our criteria for page rendering fidelity is **"As a student I am able to do my homework"**. The main content of the page must be readable but the page doesn't have to look exactly the same as it does un-proxied. Parts of the page can be different, missing, or even broken, as long as the page is still rendered well enough for students to be able to complete their annotation assignments.

## Research Questions

The outcome of this spike should be answers (written up on this GitHub issue) to the following research questions:

- [ ] How much rewriting is needed full stop?

  We want to do as little rewriting as possible because it'll reduce load on our servers, simplify our code, take less time to implement, and cause less breakage of web pages. But we don't know how little rewriting we can get away with.

  We'll fill out [the spreadsheet](https://docs.google.com/spreadsheets/d/14rldiXZKlDC7ZzWOIvC5Ky8bgxJhBOIGgE6NWroaNJQ/) to answer this question.

- [ ] How much of the rewriting that is needed can be done client-side, rather than server-side?

  We want to do as much of the rewriting as possible client-side because it'll reduce load on our servers, it'll simplify our backend code, it may allow us to implement our backend more efficiently (because if it turns out that we only need a little server-side rewriting then we can just do that little bit in Nginx with regexes), and it allows us to take advantage of the browser's proper DOM API.

## Iterative Research Strategy

Research should proceed by using the following iterative loop:

* Begin by creating an HTML rewriting proxy that just injects the `<script>` tag for the Hypothesis client, and does nothing else. This implementation is only meant to be research code, not production code (but we'll have to deploy it behind a feature flag in order to test it). And then enter this loop:
  * Test the app with the test URLs
  * If you find a problem with the page then:
    * Add a row for the problem to  [the spreadsheet](https://docs.google.com/spreadsheets/d/14rldiXZKlDC7ZzWOIvC5Ky8bgxJhBOIGgE6NWroaNJQ/) and fill it in
    * According to the scope above ("as a student I am able to do my homework"): is fixing this problem in scope?
      * If not: move on to the next test URL
      * If it is in scope: fix this one issue; deploy the fix; re-test the test URL

Use common sense: if it's too hard / not worth fixing, throw the test URL out of the test set and pick another one.

## Research Code
  
We'll need to actually write and deploy an HTML rewriting proxy in order to answer the questions above. But any code written for this spike will be considered to be research code, not product code. Based on the answers to this spike we'll then decide on the approach to implementing the production rewriting proxy.

**Comment by hmstepanek** [comment]
@seanh I think we already have an answer to this question based on the research I already did a couple months ago:
* server side: style sheets need to be proxied
* client side: any fetch calls issued from the page after loading (basically monkey patch xmlHttpRequests)

Note in my previous findings I did not need to proxy script hrefs. As I recall, near the end of my work on this I was also having to replace some links inside the stylesheets so I had made a special endpoint for stylesheets similar to legacy via.

**Comment by seanh** [comment]
Notes from sync with Hannah:

* We need to add some more test URLs to the set (https://docs.google.com/document/d/15ngwKS1EoDVZE1JRDHLG3N0Y-XeCjCnxR9HhVASzrhA/edit) because some of them are repeated and we want to have 50 unique ones, and 50 _different domains_ not multiple URLs from the same domain

**Comment by jon-betts** [comment]
I've replaced this ticket with more of a gap analysis rather than a definitive answer (which make not be possible to reach in a good timeframe): https://github.com/hypothesis/via3/issues/154
