### ISSUE TITLE
cannot use via in an iframe

### ISSUE THREAD

**Issue by judell** [hypothesis/via#76]
https://github.com/hypothesis/via/commit/ee9451edfa871fcf27bb58edf53cace088ca75f3 was the solution to https://github.com/hypothesis/h/issues/2190.

I don't know if it was true when that commit was applied, but it's true now that this prevents embedding a via page in an iframe. 

Testing the problem page in https://github.com/hypothesis/h/issues/2190, https://via.hypothes.is/http://blogs.plos.org/scicomm/2015/04/13/hello-world/, without the above commit seems unproblematic. Was it really solving a problem? If not can we revert? It's useful to be able to iframe via (and necessary for one kind of  Canvas integration).

**Comment by robertknight** [comment]
This was fixed as part of work on the LMS app.
