### ISSUE TITLE
Update Via to PDF.js v2

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#81]
The version of PDF.js used by the browser extension was updated in https://github.com/hypothesis/browser-extension/pull/9 . The version used by Via also needs updating.

One way to approach this would be to adapt the [tools/update-pdfjs](https://github.com/hypothesis/browser-extension/blob/master/tools/update-pdfjs) script in the browser-extension repository.

**Essential sub-tasks:**

- [x] Update Via to PDF.js v2 behind a feature flag
- [x] Resolve sporadic failure to load PDF ([see comment](https://github.com/hypothesis/via/issues/81#issuecomment-530800859) and [PR](https://github.com/hypothesis/via/pull/181))
- [x] Resolve issue with missing `Promise.prototype.finally` polyfill in IE 11 ([see comment](https://github.com/hypothesis/via/issues/81#issuecomment-530686096) and [PR](https://github.com/hypothesis/via/pull/182))
- [x] Do testing with a variety of PDFs and determine whether we can make PDF.js v2 the default or if additional work in the client is needed ([Slack notes](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1568878929068600), [Testing tools](https://github.com/hypothesis/anchoring-test-tools)).
- [x] Enable the feature by default (either remove the feature flag or invert it)

**Nice-to-have sub-tasks:**

- [ ] Consider minifying the main PDF.js source files (eg. using terser) to reduce startup time

**Comment by dwhly** [comment]
May be related to https://github.com/hypothesis/client/issues/608

**Comment by klemay** [comment]
[As discussed in Slack today](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1565282068025300), the version of PDF.js we ship in Via is presenting issues in the LMS context. 

There are recurring issues with orphaning annotations in the LMS app which may or may not be related to this as well (https://github.com/hypothesis/lms/issues/875).

Jon has collected data on how an upgrade would affect anchoring of past annotations here: https://github.com/judell/h_puppeteer/blob/master/results2.md

This sprint, we should decide: 
1. Partial upgrade or upgrade all the way?
2. Partial rollout (i.e., just for Via) or roll out for client and Via?
3. Once the first two items are decided, we need a sprint-ready card that reflects the scope of the work we're doing so it can be prioritized accordingly.

**Note: we are not aiming to perform the upgrade this sprint, just to make decisions on items 1 and 2 above, and carry out item 3, which is to create a sprint-ready card.**

**Comment by judell** [comment]
I vote for just via as a first step.

**Comment by robertknight** [comment]
It looks like updating Via to the latest version of PDF.js may be a dependency for resolving https://github.com/hypothesis/lms/issues/890, as otherwise we could end up spending a lot of time trying to debug and work around an issue which no longer applies.

Work on this is happening in https://github.com/hypothesis/via/pull/177.

**Comment by robertknight** [comment]
PDF.js v2 has been added to Via behind a feature flag. To activate it, add `?via.features=pdfjs` to any Via PDF URL.

H folks, see https://hypothes-is.slack.com/archives/C0C6BDS1H/p1568266978010700 for more details.

**Comment by robertknight** [comment]
There is currently an issue in IE with some of the required polyfills not being loaded:

<img width="580" alt="Screenshot 2019-09-12 07 28 47" src="https://user-images.githubusercontent.com/2458/64759544-505d9400-d52f-11e9-8506-d244e2df1f72.png">

**Comment by robertknight** [comment]
This is now done and deployed. The one remaining task which is tracked separately in https://github.com/hypothesis/product-backlog/issues/1062 is removing the PDF.js v1 feature flag.
