### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on ar5iv.labs.arxiv.org

### ISSUE THREAD

**Issue by chrisdaaz** [hypothesis/via#863]
Via throws an SSL error attempting to embed articles from [ar5iv](https://ar5iv.labs.arxiv.org/), a website that has converted [arxiv](https://arxiv.org/) articles from LaTeX to HTML. This is reproducible in an LMS environment.

### Steps to reproduce

1. Visit an article: https://ar5iv.labs.arxiv.org/html/2205.09940
2. Visit the same article in via: https://via.hypothes.is/https://ar5iv.labs.arxiv.org/html/2205.09940

### Expected behaviour

Via should be able to load the article alongside the Hypothesis sidebar.

### Actual behaviour

```
UpstreamServiceError: HTTPSConnectionPool(host='ar5iv.labs.arxiv.org', port=443): Max retries exceeded with url: /html/2205.09940 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

URL: https://via.hypothes.is/https://ar5iv.labs.arxiv.org/html/2205.09940

Third party URL: https://ar5iv.labs.arxiv.org/html/2205.09940
```

![image](https://user-images.githubusercontent.com/24395592/213247991-ac43f21f-d5b3-4c4e-9a90-22da22550b3b.png)

### Additional Information

[arxiv.org](https://arxiv.org) articles seem to work as expected. 

- https://via.hypothes.is/https://arxiv.org/pdf/2301.07111.pdf
- https://via.hypothes.is/https://arxiv.org/abs/2301.07111

_Originally posted by @chrisdaaz in https://github.com/hypothesis/product-backlog/issues/1270#issuecomment-1387426585_

### Next steps

> check that we've got [certifi](https://github.com/certifi/python-certifi) set up and up to date in Via

From: https://github.com/hypothesis/product-backlog/issues/1270#issuecomment-1387441996

**Comment by chrisdaaz** [comment]
Support ticket for customer follow-up: https://app.hubspot.com/contacts/6291320/ticket/1378515515

**Comment by chrisdaaz** [comment]
@robertknight can we add this to the support board?

Also seeing this at another school: https://app.hubspot.com/contacts/6291320/ticket/1403915869

Also happening with this: https://mathstat.slu.edu/~speegle/_book/preface.html#

Via: https://via.hypothes.is/https://mathstat.slu.edu/~speegle/_book/preface.html#

**Comment by robertknight** [comment]
> @robertknight can we add this to the support board?

Sure. Talk with the other support/CS folks and @darylhedley, but my understanding is that the support/CS teams own the Inbox on the support board and handle prioritizing items within it, and then engineering pulls from that when it has allocated time to work on these. Obviously if something super urgent comes up (eg. service is down) we would stop what we're otherwise doing and deal with it immediately.

**Comment by chrisdaaz** [comment]
Right. I just mean that my user account doesn't have permissions in this repository to add this GH Issue to the `Support board` Project.

**Comment by robertknight** [comment]
Hmm... I would have thought that only write access to the project board is required, which everyone in the organization should have. I can certainly change the permissions if needed. Do you get a specific error when trying to add this issue to the board? Are there other repos in the org from which you can add issues to the board?

**Comment by mkdir-washington-edu** [comment]
Additional ticket: https://app.hubspot.com/contacts/6291320/ticket/1403915869

**Comment by chrisdaaz** [comment]
No errors. I just don't get the gear icons:

![image](https://user-images.githubusercontent.com/24395592/215855200-a3dd9bb8-d85d-4cef-a129-d489dedc3fcc.png)

I haven't check all repos, but I can add issues to boards, and edit labels, etc. on `hypothesis/lms` but not `hypothesis/client`

**Comment by robertknight** [comment]
The issue is that this server is not returning a full chain of certificates. Browsers have a mechanism to fetch the missing certificates, but Python doesn't support it out of the box. See https://github.com/hypothesis/product-backlog/issues/1417#issuecomment-1421198847 for notes and workaround info.

**Comment by chrisdaaz** [comment]
The problem with [https://ar5iv.labs.arxiv.org](https://ar5iv.labs.arxiv.org/) certificates has been resolved by the website maintainers. The original user who reported this issue has been updated that ar5iv documents now work with via. 

Closing this as a duplicate of https://github.com/hypothesis/product-backlog/issues/1417
