### ISSUE TITLE
Loading Hypothesis doesn't work on pages without <head>

### ISSUE THREAD

**Issue by janpaul123** [hypothesis/via#9]
The HTML spec [doesn't require a `<head>` tag to be present](http://webdesign.about.com/od/beginningtutorials/qt/html-quick-and-dirty.htm). But your insertion algorithm [does assume a head to be present](https://github.com/ikreymer/pywb/blob/b379d15066445c58ff65d7f88018b51625d125ec/pywb/rewrite/rewrite_content.py#L237).

You can see this break in this example: https://via.hypothes.is/http://webdesign.about.com/od/examples/l/z-html4-minimal-document.htm

Note that this is not completely hypothetical. At Factlink we ran into this problem with real webpages, though I have to admit I don't have an example handy right now. Our algorithm solves for this and proved pretty reliable: https://github.com/Factlink/web-proxy/blob/b24c5af013583311eeb7a9370cae652a30cc3eea/lib/html_editor.rb

It also prevents from accidentally injecting into a comment, like `<!-- some talk about <head> blah blah -->`.

**Comment by ikreymer** [comment]
Hi, thanks for pointing this out, although this happens in a much more limited case than all pages w/o head tags.

The execution path you point out is actually a special banner-insert only mode, which skips the html parsing and attempts to insert a head through regex. (Currently only used for proxy mode I believe).

The general path goes through the HTMLRewriter, which has this:
https://github.com/ikreymer/pywb/blob/master/pywb/rewrite/html_rewriter.py#L181

It takes a similar approach in detecting the first non-head tag, https://github.com/ikreymer/pywb/blob/master/pywb/rewrite/html_rewriter.py#L70

So if the page has any non-head tags, things should work correctly. But of course, as your example points out, its possible that a page only has head tags like title and no other tag. This seems much less likely to actually occur though, but should be fixed.

In such a case, I think, the only option is to add the head insert at the end, when the parser is being closed, if it hasn't been inserted already.

**Comment by janpaul123** [comment]
Ah, excellent, in that case it's not nearly as severe a problem. Thanks for explaining!
