### ISSUE TITLE
Better support for caption languages in Via

### ISSUE THREAD

**Issue by marcospri** [hypothesis/via#928]
The language option in Via proposed in https://github.com/hypothesis/via/pull/914/files#diff-4dd4cf05633125f66621c5410d01c7db63d90dddd99720e27680d228c11ecb29R49

is very naive. It will need to at least:

- Be aware of variations in code languages, if picking "en" as the prefered language it should pick either "es-GB" or "es-US". Now it won't pick any of those.

- ~~It should accommodate for https://github.com/hypothesis/lms/issues/5406 where language is not "preferred" but already selected. If that language is not available for some reason it should fail instead of presenting other language.~~

**Comment by seanh** [comment]
Closing this because I don't think we need a separate issue, it's part of https://github.com/orgs/hypothesis/projects/118/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Linked+pull+requests%22%2C%22Labels%22%2C%22Repository%22%5D&pane=issue&itemId=28550553
