### ISSUE TITLE
Capture appropriate metadata with video transcript annotations

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#941]
As part of https://github.com/hypothesis/product-backlog/issues/1433 we'll need to decide what metadata should be captured when annotating video transcripts, both for the video as a whole and for the specific part of a video that an annotation refers to.

In the existing YouTube video annotation prototype in [docdrop](https://docdrop.org), the Hypothesis client just sees the transcript as a regular web page and annotations of the transcript work like annotating text on any other page. I think we are going to want to capture the timestamp and video length as metadata, so we can display that information in the sidebar/notebook or other places.

Issues to resolve:

- Decide what the annotation's main URL should be
- Decide what document-level metadata should be captured (eg. video title, channel, video length, other?)
- Decide what annotation-level metadata should be captured (eg. start/end timestamp)
- Figure out the mechanisms for the [video player app](https://github.com/hypothesis/via/issues/904) to convey the document-level metadata to the client 
- Figure out the mechanisms for the video player app to convey annotation-level metadata to the client
- Decide if we're going to display any of the video-oriented metadata (eg. timestamps) in the sidebar

Sub-tasks:

- [x] Capture YouTube video URL as annotation URL (see https://github.com/hypothesis/via/pull/1015)
- [x] Capture video title as document title (see https://github.com/hypothesis/via/issues/1071)
- [x] Capture timestamp selectors with annotations (https://github.com/hypothesis/client/pull/5655, https://github.com/hypothesis/via/pull/1116)

**Comment by robertknight** [comment]
I moved this to Via repo because that is where the video player implementation currently lives.

**Comment by robertknight** [comment]
Related to this, we've been discussing showing the video player when proxying a YouTube video URL through Via (`https://via.hypothes.is/https://www.youtube.com/watch?v=abc`), instead of a custom URL (`https://via.hypothes.is/video/abc`). If we do this, and we use eg. `https://www.youtube.com/watch?v=abc` as the URL for a video transcript annotation, we'll have a need to disambiguate from annotations made using eg. the browser extension accessing that URL as a normal web page.

The web annotations specs have a notion of [Rendering Software](https://www.w3.org/TR/annotation-model/#rendering-software) and a `renderedVia` attribute for annotation targets as a way to indicate what tool was used to render a URL. So one option would be to leverage that somehow. There is also a notion of [resource states](https://www.w3.org/TR/annotation-model/#states) as a way to indicate which format of a resource was accessed.

If we go for the `renderedVia` route, an annotation might look something like this:

```js
{
  "id": "FqhHmgR_Ee633sNKQNRUKg",
  "created": "2023-06-06T15:30:38.219849+00:00",
  "updated": "2023-06-06T15:30:38.219849+00:00",
  "user": "acct:robertknight@hypothes.is",
  "uri": "https://www.youtube.com/watch?v=x8TO-nrUtSI",
  "text": "A test annotation.",
  "group": "__world__",
  "target": [
    {
      "source": "https://www.youtube.com/watch?v=x8TO-nrUtSI",
      "renderedVia": "<Video player URL>",
      "selector": [
        {
          "end": 223,
          "type": "TextPositionSelector",
          "start": 200
        },
        {
          "type": "TextQuoteSelector",
          "exact": "ridge racer or tekken 2",
          "prefix": " the floor when you first saw a ",
          "suffix": ". these were very faithful arcad"
        }
        // TODO - Add timestamp selector
      ]
    }
  ],
  "document": {
    "title": [
      "<Video title>"
    ]
  }
}
```

We'd need to come up with some URL to represent the video player for use with `renderedVia`.

**Comment by robertknight** [comment]
Annotations in the video player currently capture XPath range selectors. This is wasteful because these selectors will become invalid when we change the UI of the video player:

```json
{
  "type": "RangeSelector",
  "endOffset": 8,
  "startOffset": 21,
  "endContainer": "/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[7]/p[1]",
  "startContainer": "/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[6]/p[1]"
}
```

This reminds me, we should check whether any of the top-level `div`s should be replaced by more semantic elements.

**Comment by lyzadanger** [comment]
When viewing the video app using a via URL pattern like so, which is **what (localhost) via will currently redirect you to if you paste a YouTube video URL in the landing-page input field**:

http://localhost:9083/https://www.youtube.com/watch?v=eOJ6L_snYnA

via URI parameters are not getting stripped on annotations created for such videos. This results in annotations having `uri`s such as:

```
http://localhost:9083/video/youtube?via.client.ignoreOtherConfiguration=1&via.client.openSidebar=1&via.external_link_mode=new-tab&v=eOJ6L_snYnA&url=https://www.youtube.com/watch?v=eOJ6L_snYnA&via.sec=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoIjoibEp6TWdtTHo4aU00Wnowc3Q4UjIiLCJleHAiOjE2ODcyODIyMDB9.7jEHgFxSBm2dXyMAHuekEo8JazbiypL3CDWWW1kp-mc

http://localhost:9083/video/youtube?via.client.ignoreOtherConfiguration=1&via.client.openSidebar=1&via.external_link_mode=new-tab&v=eOJ6L_snYnA&url=https://www.youtube.com/watch?v=eOJ6L_snYnA&via.sec=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoIjoibEp6TWdtTHo4aU00Wnowc3Q4UjIiLCJleHAiOjE2ODcyODc2MDB9.CSVVvo5n8v8R2KJZi3uYSIjtpvt9ZrVvKuUx9hgEZ6c
```

Those two should be the for annotations associated with the same document, but are not. Annotations fail to load after `via.sec` changes, which happens relatively frequently.

The net result is that annotations fail to load for the video.

I'm updating my local bookmarks to use this URL pattern:

http://localhost:9083/video/youtube?url=https://www.youtube.com/watch?v=eOJ6L_snYnA

at which the URI parameters do appear to be stripped from the video-document URI.

Visiting the video app at this URL pattern also resolves https://github.com/hypothesis/via/issues/991 for me.

**Comment by robertknight** [comment]
The issues Lyza mentioned above are fixed in https://github.com/hypothesis/via/pull/1015.
