### ISSUE TITLE
Show sidebar alongside transcript

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#954]
In the video player app, make it possible to see the transcript alongside the sidebar. This will make it possible to read the transcript and annotation threads at the same time, like side-by-side mode for PDFs or web pages.

In the current implementation, the sidebar displays on top of the transcript:

<img width="1407" alt="Video player snapshot" src="https://github.com/hypothesis/via/assets/2458/004fa29e-a166-4ce9-a471-cc93dafbf3b8">

The current tentative design idea is to make it so that when the sidebar is open, the transcript is displayed underneath the video instead.

**Comment by robertknight** [comment]
https://github.com/hypothesis/via/issues/952 is connected to this. If we move the transcript container under the video, it is going to be even more valuable than it is now to display the bucket bar alongside the transcript rather than as part of the sidebar.

**Comment by robertknight** [comment]
This is now implemented, based on Hypothesis's side-by-side mode for HTML, but with some hacks in Via to gain more control over positioning. See https://github.com/hypothesis/client/issues/5571.

**Comment by lyzadanger** [comment]
Update: this ticket will be done when we implement a mechanism for the video player to be able to style its own "side-by-side mode" independent of the client. i.e. it should be possible for the host page to disabled side-by-side mode, and respond to the current layout state of the sidebar in whatever way it sees fit. The layout should also be less awkward across all breakpoints.

**Comment by lyzadanger** [comment]
Complete as of https://github.com/hypothesis/via/pull/1083

**Comment by nhan000** [comment]
How can I have this interface here?
![](https://user-images.githubusercontent.com/2458/243326817-004fa29e-a166-4ce9-a471-cc93dafbf3b8.png)

Is there anything from the `project: video annotations` people can try out yet? If not, where I can follow the development to know when it's ready? Will there be an ability to annotate offline video? I'm somewhat familiar with https://docdrop.org/ but this is a separate thing right? Thanks a lot!
