### ISSUE TITLE
Add a Via backend API for getting YouTube video transcripts

### ISSUE THREAD

**Issue by seanh** [hypothesis/via#990]
To be called by Via's own frontend in order to get the transcript of the current video.

**Comment by seanh** [comment]
Proposed API Design
===================

## Request

Request that Via's frontend will send to Via's backend to get a transcript:

```
GET /api/youtube/transcripts/1 HTTP/1.1
Authorization: Bearer {token}
```

## Response

Response that Via's backend will send back to Via's frontend:

```
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "transcripts",
    "id": "1",
    "attributes": {
      "segments": [
        {"text": "...", "start": 0.0},
        ...
      ],
    }
  }
}
```

## Error responses

* If the given transcript ID isn't found the response will be a 404 (no body).

* If the Authorization header is missing or invalid the response will be a 403 (no body).

* If something goes wrong with fetching the transcript from the YouTube API the response will be a 500 with a JSON body something like this:

  ```
  HTTP/1.1 500 Internal Server Error
  Content-Type: application/vnd.api+json

  {
    "errors": [
      {
        "status": "500",
        "code": "<machine_readable_error_code>",
        "title": "<human_readable_summary>",
        "detail": "<more_detailed_human_readable_explanation",
      }
    ]
  }
  ```

  `"code"`, `"title"` and `"detail"` are all optional in error objects. `"status"` "should" be present. Every error object must contain at least one of these.

  I'm not sure why the HTTP status code is repeated in the body, especially since this introduces the possibility of the status in the body differing from the status in the HTTP headers and also of multiple statuses in the body differing from each other (since `"errors"` is an array that can contain multiple error objects), but that's what JSON:API tells you to do. See [errors in JSON:API](https://jsonapi.org/format/#errors).

## How the backend will configure the frontend

Via's backend currently passes a JSON config object to the frontend as an `"application/json"` script in the HTML:

https://github.com/hypothesis/via/blob/972c15cfea3cfdf42e35896ab26c07437b1e34ff/via/templates/view_video.html.jinja2#L14-L20

We'll add configuration to this JSON config telling the frontend how to call the transcripts API:

```json
{
  "api": {
    "transcript": {
      "doc": "Get the transcript of the current video",
      "url": "https://via.hypothes.is/api/youtube/transcripts/1",
      "method": "GET",
      "headers": {
        "Authorization": "Bearer {token}"
      }
    }
  }
}
```

This way if the backend ever needs to change the API request (for example to change the path, or to add a query param or header) that is a backend-only change: the backend can just change the config it sends to the frontend and that will change the request that the frontend sends without changing any frontend code.

We could also add JSON body params to this config for `POST` requests but it's not needed for getting transcripts.

## Design influences

The API design is based on:

* The API that LMS's backend provides to LMS's frontend. Particularly the use of short-lived JWTs as bearer tokens in `Authorization` headers for authentication, and how the backend will pass API configuration to the frontend in a JSON object embedded in the page HTML
* [JSON:API](https://jsonapi.org/), particularly for the shape of the JSON response bodies
* The [hard-coded transcript](https://github.com/hypothesis/via/blob/972c15cfea3cfdf42e35896ab26c07437b1e34ff/via/static/scripts/video_player/sample-transcript.ts#L8-L1392) currently in the frontend code, for the shape of the transcript itself (the segments array). But note that [duration is not needed](https://hypothes-is.slack.com/archives/C054CG5PH5M/p1686675648037879?thread_ts=1686672889.519289&cid=C054CG5PH5M)

Other considerations
--------------------

* You might think that authentication isn't needed at all since this is just an API for fetching publicly available transcripts. Why not have the API be completely unauthenticated and therefore cacheable in Cloudflare? But I think we may not want to allow open public access to this API

* What about authorization? Can anyone with a valid token request any transcript? If they got their access token by launching an LMS assignment for a particular video, shouldn't they only be able to use the token to fetch the transcript for _that_ video?

  We may be able to do this by encoding the allowed transcript IDs (or more generally: the allowed API requests) into the JWT authorization token but it may not be worth the effort.

  We might also consider making the token IDs that the API accepts be randomly generated rather than exposing the DB's predictable autoincrementing integers.

**Comment by robertknight** [comment]
Related to this, it would be useful to have an API to get video metadata as well, such as the title. See https://github.com/hypothesis/via/issues/999.

**Comment by robertknight** [comment]
> But I think we may not want to allow open public access to this API

I agree. There is a risk that someone ends up using our API as a proxy to mask where the traffic to YouTube is really coming from. Ensuring that the request came from a client that recently loaded Via in a browser or another trusted service in our system seems a sensible measure to make such abuse less convenient.
