### ISSUE TITLE
Red "loading bar" showing forever in video-annotation app

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/via#991]
After recent changes, there is a red "loading bar" that partially fills and never resolves at the top of the screen on the video annotation app (this is as seen in my localhost):

<img width="1579" alt="image" src="https://github.com/hypothesis/via/assets/439947/bdc0e17f-de83-4f0b-8228-681992990150">

This loading bar is outside of the `iframe` that contains the proxied content/video app.

_Update_: This behavior only happens when accessing the video-annotation app through URL patterns like:

http://localhost:9083/https://www.youtube.com/watch?v=eOJ6L_snYnA

And does not manifest with URL patterns like:

http://localhost:9083/video/youtube?url=https://www.youtube.com/watch?v=eOJ6L_snYnA

It should be noted that the first URL pattern is what Via will redirect you to if you paste a YouTube URL in the input field on via's landing page. See more discussion about the two different URL formats here: https://github.com/hypothesis/via/issues/941#issuecomment-1600764487

**Comment by seanh** [comment]
FYI this only happens in public Via (where I don't think we have immediate plans to release the new YouTube player), doesn't happen in LMS.
