### ISSUE TITLE
Make sure search is near transcript on mobile/narrow views in video app

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/via#993]
The first round of app layout adjustments stacks the interface on narrow screens, but the search bar is far removed from the transcript. Let's see if we can get the search nearer to the transcript. This may require changing source order on those narrower screens.

<img width="612" alt="Screen Shot 2023-06-15 at 3 18 04 PM" src="https://github.com/hypothesis/via/assets/439947/6c030495-f20b-4e4a-8498-8236f0236b2c">

**Comment by dwhly** [comment]
We saw this wrinkle during the investigation phase, and the [netlify mockup does do this](https://hypothesis-video-transcriptions.netlify.app/) if the organization there is helpful... 
<img width="772" alt="Screenshot 2023-06-16 at 7 56 29 AM" src="https://github.com/hypothesis/via/assets/1413074/04bca22e-7675-4ca4-9609-d020b738a114">

**Comment by lyzadanger** [comment]
> We saw this wrinkle during the investigation phase, and the [netlify mockup does do this](https://hypothesis-video-transcriptions.netlify.app/) if the organization there is helpful... 

Not as such because the search bar is part of the transcript controls, whereas in our wider-screen layout, it is not. We'll solve it, anyhow.
